#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
ENV_MANIFEST="$ROOT/scripts/llama-gpu-env-manifest.json"

SERIAL="${ANDROID_SERIAL:-}"
OUT=""
DEFAULT_PROBE_DIR="/tmp/q6write10-bundle"
DEFAULT_SPV="$DEFAULT_PROBE_DIR/native-q6.write.spv"
DEFAULT_PROBE_ENV="$DEFAULT_PROBE_DIR/noop-probe.env"
SPV="$DEFAULT_SPV"
PROBE_ENV="$DEFAULT_PROBE_ENV"
PROBE_SOURCE_SPV=""
PROBE_SOURCE_HASH=""
PROBE_LOCATOR=""
ALLOW_ARCHIVED_PROBE_SOURCE="${PDOCKER_Q6K_ALLOW_ARCHIVED_PROBE_SOURCE:-0}"
CPU_TPS="0.04702448956650603"
CPU_CTX="512"
GPU_CTX="512"
GPU_LAYERS="1"
PREDICT="4"
REPEAT="1"
PLAN_OUT="docs/test/llama-gpu-q6-preflight-plan-latest.json"
VERDICT_OUT=""
DRY_RUN=0

usage() {
  cat <<'USAGE'
Usage:
  ANDROID_SERIAL=<host:port> scripts/android-llama-gpu-q6-workgroup-run.sh [options]

Options:
  --serial SERIAL        ADB serial. Overrides ANDROID_SERIAL.
  --out PATH            Output artifact path. Defaults to docs/test/...timestamp...
  --spv PATH            Instrumented probe SPIR-V used for lowering preflight.
  --probe-env PATH      Probe environment file generated by prepare-q6k-noop-probe.sh.
  --probe-source-spv PATH
                        Actual native Q6 source SPIR-V dump used to build a fresh probe bundle.
  --probe-source-hash HASH
                        Expected source hash for --probe-source-spv and generated probe env.
  --probe-locator PATH  JSON from scripts/locate-q6-source-spirv-dump.py; fills --probe-source-spv/hash.
  --cpu-tps VALUE       CPU baseline tokens/sec to reuse.
  --cpu-ctx N           CPU baseline context size recorded in the plan and passed to compare.
  --gpu-ctx N           GPU context size recorded in the plan and passed to compare.
  --gpu-layers N        llama.cpp -ngl value. Default: 1.
  --predict N           Tokens to predict. Default: 4.
  --repeat N            Repeat count. Default: 1.
  --plan-out PATH       Pre-flight plan path. Default: docs/test/llama-gpu-q6-preflight-plan-latest.json.
  --verdict-out PATH    Plan verdict path. Defaults to <out>-plan-verdict.json.
  --dry-run             Write the pre-flight plan only. Do not touch ADB or device files.

This runner intentionally does not rebuild the llama image and does not modify
llama.cpp, Dockerfiles, models, or prompts.
USAGE
}

export_q6_required_env_overlay() {
  local env_file
  env_file="$(mktemp)"
  python3 - "$ENV_MANIFEST" >"$env_file" <<'PY'
import json
import re
import sys
from pathlib import Path

manifest_path = Path(sys.argv[1])
manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
overlay = manifest.get("q6_required_env_overlay")
if not isinstance(overlay, dict) or not overlay:
    raise SystemExit(f"missing q6_required_env_overlay in {manifest_path}")
for key, value in sorted(overlay.items()):
    if not isinstance(key, str) or not re.fullmatch(r"PDOCKER_[A-Z0-9_]+", key):
        raise SystemExit(f"invalid Q6 env key in {manifest_path}: {key!r}")
    if not isinstance(value, str) or "\n" in value or "\0" in value:
        raise SystemExit(f"invalid Q6 env value for {key} in {manifest_path}")
    print(f"{key}={value}")
PY
  while IFS= read -r line; do
    [[ -n "$line" ]] || continue
    export "$line"
  done <"$env_file"
  rm -f "$env_file"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --serial) SERIAL="${2:?missing serial}"; shift 2 ;;
    --out) OUT="${2:?missing output path}"; shift 2 ;;
    --spv) SPV="${2:?missing spv path}"; shift 2 ;;
    --probe-env) PROBE_ENV="${2:?missing probe env path}"; shift 2 ;;
    --probe-source-spv) PROBE_SOURCE_SPV="${2:?missing probe source spv path}"; shift 2 ;;
    --probe-source-hash) PROBE_SOURCE_HASH="${2:?missing probe source hash}"; shift 2 ;;
    --probe-locator) PROBE_LOCATOR="${2:?missing probe locator path}"; shift 2 ;;
    --cpu-tps) CPU_TPS="${2:?missing cpu tps}"; shift 2 ;;
    --cpu-ctx) CPU_CTX="${2:?missing cpu ctx}"; shift 2 ;;
    --gpu-ctx) GPU_CTX="${2:?missing gpu ctx}"; shift 2 ;;
    --gpu-layers) GPU_LAYERS="${2:?missing gpu layers}"; shift 2 ;;
    --predict) PREDICT="${2:?missing predict}"; shift 2 ;;
    --repeat) REPEAT="${2:?missing repeat}"; shift 2 ;;
    --plan-out) PLAN_OUT="${2:?missing plan output path}"; shift 2 ;;
    --verdict-out) VERDICT_OUT="${2:?missing verdict output path}"; shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ -n "$PROBE_LOCATOR" ]]; then
  LOCATOR_TEXT="$(python3 - "$PROBE_LOCATOR" <<'PY'
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
data = json.loads(path.read_text(encoding="utf-8"))
if data.get("schema") != "pdocker.q6k.source-spirv-dump-locator.v1":
    raise SystemExit(f"unsupported probe locator schema: {data.get('schema')}")
if data.get("valid") is not True:
    raise SystemExit(f"probe locator is not valid: {data.get('reason')}")
selected = data.get("selected") if isinstance(data.get("selected"), dict) else {}
spv = selected.get("spv")
hash_value = data.get("target_hash")
if not isinstance(spv, str) or not spv:
    raise SystemExit("probe locator selected.spv is missing")
if not isinstance(hash_value, str) or not hash_value.startswith("0x"):
    raise SystemExit("probe locator target_hash is missing")
print(spv)
print(hash_value)
PY
  )"
  mapfile -t LOCATOR_VALUES <<<"$LOCATOR_TEXT"
  if [[ "${#LOCATOR_VALUES[@]}" -ne 2 ]]; then
    echo "probe locator did not produce source spv/hash: $PROBE_LOCATOR" >&2
    exit 2
  fi
  PROBE_SOURCE_SPV="${LOCATOR_VALUES[0]}"
  PROBE_SOURCE_HASH="${LOCATOR_VALUES[1]}"
fi

if [[ -z "$OUT" ]]; then
  OUT="docs/test/llama-gpu-ngl${GPU_LAYERS}-q6-workgroup-legalized-$(date -u +%Y%m%dT%H%M%SZ).json"
fi
if [[ -z "$VERDICT_OUT" ]]; then
  VERDICT_OUT="${OUT%.json}-plan-verdict.json"
fi
if [[ -z "$SERIAL" ]]; then
  if [[ "$DRY_RUN" -eq 1 ]]; then
    SERIAL="adb-not-used"
  else
    echo "ANDROID_SERIAL or --serial is required" >&2
    exit 2
  fi
fi

echo "[pdocker q6 workgroup] plan: $PLAN_OUT"
python3 scripts/plan-llama-gpu-q6-run.py \
  --serial "$SERIAL" \
  --artifact "$OUT" \
  --cpu-tps "$CPU_TPS" \
  --cpu-ctx "$CPU_CTX" \
  --gpu-ctx "$GPU_CTX" \
  --gpu-layers "$GPU_LAYERS" \
  --predict "$PREDICT" \
  --repeat "$REPEAT" \
  --out "$PLAN_OUT"

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "[pdocker q6 workgroup] dry-run complete; no ADB, SPIR-V, probe-env, or compare step was executed."
  exit 0
fi

validate_probe_source_freshness_before_adb() {
  if [[ -n "$PROBE_SOURCE_SPV" && -z "$PROBE_SOURCE_HASH" ]]; then
    echo "[pdocker q6 workgroup] refusing before ADB: --probe-source-spv requires --probe-source-hash" >&2
    exit 2
  fi
  if [[ -z "$PROBE_SOURCE_SPV" && -n "$PROBE_SOURCE_HASH" ]]; then
    echo "[pdocker q6 workgroup] refusing before ADB: --probe-source-hash requires --probe-source-spv" >&2
    exit 2
  fi
  if [[ "$ALLOW_ARCHIVED_PROBE_SOURCE" == "1" ]]; then
    return
  fi
  if [[ -n "$PROBE_LOCATOR" ]]; then
    return
  fi
  if [[ -n "$PROBE_SOURCE_SPV" && -n "$PROBE_SOURCE_HASH" ]]; then
    return
  fi
  cat >&2 <<'EOF'
[pdocker q6 workgroup] refusing before ADB: actual Q6 probe source freshness is required.
Pass --probe-locator <locator.json>, or pass both --probe-source-spv <actual Q6 source SPIR-V dump>
and --probe-source-hash <actual source hash>. Set PDOCKER_Q6K_ALLOW_ARCHIVED_PROBE_SOURCE=1 only
for archived fixture/regression runs.
EOF
  exit 2
}

validate_probe_source_freshness_before_adb

if [[ "$SPV" == "$DEFAULT_SPV" && "$PROBE_ENV" == "$DEFAULT_PROBE_ENV" ]]; then
  SOURCE_SPV="$PROBE_SOURCE_SPV"
  if [[ -z "$SOURCE_SPV" && "$ALLOW_ARCHIVED_PROBE_SOURCE" == "1" ]]; then
    SOURCE_SPV="$ROOT/docs/test/spirv-q6k-native-adb45055/native-q6-source.spv"
  fi
  NEED_PREPARE=0
  TOOLING_STALE=0
  if [[ ! -f "$SPV" || ! -f "$PROBE_ENV" ]]; then
    NEED_PREPARE=1
  elif [[ "$SPV" -ot "$ROOT/scripts/instrument-spirv-noop-probe.py" ||
          "$SPV" -ot "$ROOT/scripts/analyze-spirv.py" ||
          "$SPV" -ot "$ROOT/scripts/prepare-q6k-noop-probe.sh" ||
          "$PROBE_ENV" -ot "$ROOT/scripts/instrument-spirv-noop-probe.py" ||
          "$PROBE_ENV" -ot "$ROOT/scripts/analyze-spirv.py" ||
          "$PROBE_ENV" -ot "$ROOT/scripts/prepare-q6k-noop-probe.sh" ]]; then
    TOOLING_STALE=1
    NEED_PREPARE=1
  elif [[ -n "$SOURCE_SPV" && ( "$SPV" -ot "$SOURCE_SPV" || "$PROBE_ENV" -ot "$SOURCE_SPV" ) ]]; then
    NEED_PREPARE=1
  elif [[ -n "$PROBE_SOURCE_HASH" ]]; then
    CURRENT_PROBE_HASH="$(set -a; . "$PROBE_ENV"; printf '%s' "${PDOCKER_GPU_SPIRV_PROBE_EXPECTED_HASH:-}")"
    if [[ "${CURRENT_PROBE_HASH,,}" != "${PROBE_SOURCE_HASH,,}" ]]; then
      NEED_PREPARE=1
    fi
  fi
  if [[ "$NEED_PREPARE" -eq 1 ]]; then
    if [[ -z "$SOURCE_SPV" ]]; then
      cat >&2 <<EOF
[pdocker q6 workgroup] refusing to refresh the default probe bundle from the archived fixture.
The existing default probe bundle is missing or stale; tooling_stale=${TOOLING_STALE}.
Pass --probe-source-spv <actual Q6 source SPIR-V dump> and --probe-source-hash <actual source hash>,
or set PDOCKER_Q6K_ALLOW_ARCHIVED_PROBE_SOURCE=1 only for fixture/regression runs.
EOF
      exit 2
    fi
    PREPARE_ARGS=(scripts/prepare-q6k-noop-probe.sh --spv "$SOURCE_SPV" --out-dir "$DEFAULT_PROBE_DIR" --probe-writes)
    if [[ -n "$PROBE_SOURCE_HASH" ]]; then
      PREPARE_ARGS+=(--expected-hash "$PROBE_SOURCE_HASH")
    fi
    echo "[pdocker q6 workgroup] refreshing default probe bundle from: $SOURCE_SPV"
    bash "${PREPARE_ARGS[@]}" >/dev/null
  fi
fi

if [[ ! -f "$SPV" ]]; then
  echo "missing Q6 SPIR-V sample: $SPV" >&2
  exit 2
fi
if [[ ! -f "$PROBE_ENV" ]]; then
  echo "missing probe env: $PROBE_ENV" >&2
  exit 2
fi

set -a
# shellcheck source=/dev/null
. "$PROBE_ENV"
set +a
if [[ -n "$PROBE_SOURCE_HASH" ]]; then
  OBSERVED_PROBE_HASH="${PDOCKER_GPU_SPIRV_PROBE_EXPECTED_HASH:-}"
  if [[ "${OBSERVED_PROBE_HASH,,}" != "${PROBE_SOURCE_HASH,,}" ]]; then
    echo "[pdocker q6 workgroup] probe env hash mismatch: expected $PROBE_SOURCE_HASH got ${OBSERVED_PROBE_HASH:-<missing>}" >&2
    exit 2
  fi
fi
export_q6_required_env_overlay

if [[ -z "${PDOCKER_GPU_SPIRV_PROBE_MANIFEST:-}" || ! -f "${PDOCKER_GPU_SPIRV_PROBE_MANIFEST:-}" ]]; then
  echo "[pdocker q6 workgroup] missing probe manifest from probe env" >&2
  exit 2
fi
if [[ -z "${PDOCKER_GPU_SPIRV_PROBE_SHADER:-}" || ! -f "${PDOCKER_GPU_SPIRV_PROBE_SHADER:-}" ]]; then
  echo "[pdocker q6 workgroup] missing probe shader from probe env" >&2
  exit 2
fi
if [[ "$PDOCKER_GPU_SPIRV_PROBE_SHADER" != "$SPV" ]]; then
  echo "[pdocker q6 workgroup] probe env shader mismatch: expected $SPV got $PDOCKER_GPU_SPIRV_PROBE_SHADER" >&2
  exit 2
fi

echo "[pdocker q6 workgroup] probe manifest verify: $PDOCKER_GPU_SPIRV_PROBE_MANIFEST"
python3 scripts/verify-spirv-probe-manifest.py \
  "$PDOCKER_GPU_SPIRV_PROBE_MANIFEST" \
  --json-out docs/test/q6-probe-manifest-verify-latest.json

echo "[pdocker q6 workgroup] preflight: $SPV"
python3 scripts/maintenance/verify-q6-workgroup-lowering-preflight.py \
  "$SPV" \
  --expect-spec-id 0 \
  --expect-value 32 \
  --json-out docs/test/q6-workgroup-lowering-preflight-latest.json

echo "[pdocker q6 workgroup] readiness: $SERIAL"
ANDROID_SERIAL="$SERIAL" \
bash scripts/android-llama-gpu-readiness.sh \
  --out docs/test/llama-gpu-readiness-q6-workgroup-latest.json

echo "[pdocker q6 workgroup] compare output: $OUT"
ANDROID_SERIAL="$SERIAL" \
PDOCKER_ADB_KEEPALIVE="${PDOCKER_ADB_KEEPALIVE:-1}" \
PDOCKER_ANDROID_SAME_DEVICE_HTTP="${PDOCKER_ANDROID_SAME_DEVICE_HTTP:-1}" \
bash scripts/android-llama-gpu-compare.sh \
  --gpu-only \
  --cpu-tps "$CPU_TPS" \
  --cpu-ctx "$CPU_CTX" \
  --gpu-ctx "$GPU_CTX" \
  --gpu-layers "$GPU_LAYERS" \
  --predict "$PREDICT" \
  --repeat "$REPEAT" \
  --out "$OUT"

echo "[pdocker q6 workgroup] verify: $OUT"
set +e
python3 scripts/verify-llama-gpu-artifact.py "$OUT" --require-q6-workgroup-clear
VERIFY_RC=$?
set -e

echo "[pdocker q6 workgroup] verdict: $VERDICT_OUT"
set +e
python3 scripts/verify-llama-gpu-q6-run-against-plan.py \
  --plan "$PLAN_OUT" \
  --artifact "$OUT" \
  --out "$VERDICT_OUT" \
  --allow-nonterminal
VERDICT_RC=$?
set -e

if [[ "$VERIFY_RC" -ne 0 ]]; then
  echo "[pdocker q6 workgroup] artifact verifier exited with $VERIFY_RC; verdict was still written to $VERDICT_OUT" >&2
  exit "$VERIFY_RC"
fi
if [[ "$VERDICT_RC" -ne 0 ]]; then
  echo "[pdocker q6 workgroup] plan verdict exited with $VERDICT_RC" >&2
  exit "$VERDICT_RC"
fi
