#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

SERIAL="${ANDROID_SERIAL:-}"
OUT=""
SPV="/tmp/q6write10-bundle/native-q6.write.spv"
PROBE_ENV="/tmp/q6write10-bundle/noop-probe.env"
CPU_TPS="0.04702448956650603"
CPU_CTX="512"
GPU_CTX="512"
GPU_LAYERS="1"
PREDICT="4"
REPEAT="1"
PLAN_OUT="docs/test/llama-gpu-q6-preflight-plan-latest.json"
VERDICT_OUT=""
DRY_RUN=0

usage() {
  cat <<'USAGE'
Usage:
  ANDROID_SERIAL=<host:port> scripts/android-llama-gpu-q6-workgroup-run.sh [options]

Options:
  --serial SERIAL        ADB serial. Overrides ANDROID_SERIAL.
  --out PATH            Output artifact path. Defaults to docs/test/...timestamp...
  --spv PATH            Native Q6 SPIR-V sample for lowering preflight.
  --probe-env PATH      Probe environment file generated by prepare-q6k-noop-probe.sh.
  --cpu-tps VALUE       CPU baseline tokens/sec to reuse.
  --gpu-layers N        llama.cpp -ngl value. Default: 1.
  --predict N           Tokens to predict. Default: 4.
  --repeat N            Repeat count. Default: 1.
  --plan-out PATH       Pre-flight plan path. Default: docs/test/llama-gpu-q6-preflight-plan-latest.json.
  --verdict-out PATH    Plan verdict path. Defaults to <out>-plan-verdict.json.
  --dry-run             Write the pre-flight plan only. Do not touch ADB or device files.

This runner intentionally does not rebuild the llama image and does not modify
llama.cpp, Dockerfiles, models, or prompts.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --serial) SERIAL="${2:?missing serial}"; shift 2 ;;
    --out) OUT="${2:?missing output path}"; shift 2 ;;
    --spv) SPV="${2:?missing spv path}"; shift 2 ;;
    --probe-env) PROBE_ENV="${2:?missing probe env path}"; shift 2 ;;
    --cpu-tps) CPU_TPS="${2:?missing cpu tps}"; shift 2 ;;
    --gpu-layers) GPU_LAYERS="${2:?missing gpu layers}"; shift 2 ;;
    --predict) PREDICT="${2:?missing predict}"; shift 2 ;;
    --repeat) REPEAT="${2:?missing repeat}"; shift 2 ;;
    --plan-out) PLAN_OUT="${2:?missing plan output path}"; shift 2 ;;
    --verdict-out) VERDICT_OUT="${2:?missing verdict output path}"; shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ -z "$OUT" ]]; then
  OUT="docs/test/llama-gpu-ngl${GPU_LAYERS}-q6-workgroup-legalized-$(date -u +%Y%m%dT%H%M%SZ).json"
fi
if [[ -z "$VERDICT_OUT" ]]; then
  VERDICT_OUT="${OUT%.json}-plan-verdict.json"
fi
if [[ -z "$SERIAL" ]]; then
  if [[ "$DRY_RUN" -eq 1 ]]; then
    SERIAL="adb-not-used"
  else
    echo "ANDROID_SERIAL or --serial is required" >&2
    exit 2
  fi
fi

echo "[pdocker q6 workgroup] plan: $PLAN_OUT"
python3 scripts/plan-llama-gpu-q6-run.py \
  --serial "$SERIAL" \
  --artifact "$OUT" \
  --gpu-layers "$GPU_LAYERS" \
  --predict "$PREDICT" \
  --repeat "$REPEAT" \
  --out "$PLAN_OUT"

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "[pdocker q6 workgroup] dry-run complete; no ADB, SPIR-V, probe-env, or compare step was executed."
  exit 0
fi

if [[ ! -f "$SPV" ]]; then
  echo "missing Q6 SPIR-V sample: $SPV" >&2
  exit 2
fi
if [[ ! -f "$PROBE_ENV" ]]; then
  echo "missing probe env: $PROBE_ENV" >&2
  exit 2
fi

echo "[pdocker q6 workgroup] preflight: $SPV"
python3 scripts/maintenance/verify-q6-workgroup-lowering-preflight.py \
  "$SPV" \
  --expect-spec-id 0 \
  --expect-value 32 \
  --json-out docs/test/q6-workgroup-lowering-preflight-latest.json

echo "[pdocker q6 workgroup] readiness: $SERIAL"
ANDROID_SERIAL="$SERIAL" \
bash scripts/android-llama-gpu-readiness.sh \
  --out docs/test/llama-gpu-readiness-q6-workgroup-latest.json

set -a
# shellcheck source=/dev/null
. "$PROBE_ENV"
set +a

echo "[pdocker q6 workgroup] compare output: $OUT"
ANDROID_SERIAL="$SERIAL" \
PDOCKER_GPU_CPU_ORACLE=1 \
PDOCKER_GPU_STRICT_PASSTHROUGH=1 \
PDOCKER_GPU_LEGALIZE_WORKGROUP_SIZE_FROM_SPEC=1 \
PDOCKER_GPU_MATERIALIZE_SPIRV_SPECIALIZATION_CONSTANTS=1 \
PDOCKER_GPU_DISPATCH_PROFILE_LOG=1 \
PDOCKER_GPU_DISPATCH_PROFILE_RESPONSE=1 \
bash scripts/android-llama-gpu-compare.sh \
  --gpu-only \
  --cpu-tps "$CPU_TPS" \
  --cpu-ctx "$CPU_CTX" \
  --gpu-ctx "$GPU_CTX" \
  --gpu-layers "$GPU_LAYERS" \
  --predict "$PREDICT" \
  --repeat "$REPEAT" \
  --out "$OUT"

echo "[pdocker q6 workgroup] verify: $OUT"
set +e
python3 scripts/verify-llama-gpu-artifact.py "$OUT" --require-q6-workgroup-clear
VERIFY_RC=$?
set -e

echo "[pdocker q6 workgroup] verdict: $VERDICT_OUT"
set +e
python3 scripts/verify-llama-gpu-q6-run-against-plan.py \
  --plan "$PLAN_OUT" \
  --artifact "$OUT" \
  --out "$VERDICT_OUT" \
  --allow-nonterminal
VERDICT_RC=$?
set -e

if [[ "$VERIFY_RC" -ne 0 ]]; then
  echo "[pdocker q6 workgroup] artifact verifier exited with $VERIFY_RC; verdict was still written to $VERDICT_OUT" >&2
  exit "$VERIFY_RC"
fi
if [[ "$VERDICT_RC" -ne 0 ]]; then
  echo "[pdocker q6 workgroup] plan verdict exited with $VERDICT_RC" >&2
  exit "$VERDICT_RC"
fi
