#!/usr/bin/env python3
"""Refresh GitHub-facing showcase documents from repository sources."""

from __future__ import annotations

import argparse
from datetime import date, timedelta
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
GENERATED = "<!-- GENERATED by scripts/update-showcase.py; do not edit by hand. -->"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_or_check(path: Path, content: str, check: bool) -> bool:
    old = path.read_text(encoding="utf-8") if path.exists() else ""
    if old == content:
        return False
    if check:
        print(f"showcase stale: {path.relative_to(ROOT)}", file=sys.stderr)
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"updated {path.relative_to(ROOT)}")
    return True


def snapshot_date(*texts: str) -> str:
    dated: list[str] = []
    versions: list[str] = []
    for text in texts:
        dated.extend(re.findall(r"Snapshot date:\s*(\d{4}-\d{2}-\d{2})", text))
        dated.extend(re.findall(r'"timestamp_utc":\s*"([^"]+)"', text))
        versions.extend(re.findall(r"Snapshot at\s*(v?\d[\w.\-]*)", text))
    if dated:
        return max(dated)
    if versions:
        return max(versions)
    return "source-controlled"


def todo_counts(todo: str) -> dict[str, int]:
    counts: dict[str, int] = {}
    for state in re.findall(r"^- \[([a-z]+)\]", todo, flags=re.MULTILINE):
        counts[state] = counts.get(state, 0) + 1
    return counts


def compat_count(compat: str, label: str) -> str:
    match = re.search(label + r"=(\d+)", compat)
    return match.group(1) if match else "unknown"


def clean_item(text: str, max_len: int = 190) -> str:
    text = re.sub(r"\s+", " ", text).strip()
    if len(text) <= max_len:
        return text
    cut = text[:max_len].rsplit(" ", 1)[0]
    return cut.rstrip(".,;:") + "..."


def active_items(todo: str, limit: int = 10) -> list[tuple[str, str]]:
    items: list[tuple[str, str]] = []
    current: list[str] = []
    state = ""
    for line in todo.splitlines():
        any_item = re.match(r"^- \[([a-z]+)\]\s+(.*)", line)
        if any_item and current:
            items.append((state, clean_item(" ".join(current))))
            current = []
            state = ""
            if len(items) >= limit:
                break
        match = re.match(r"^- \[(next|doing|blocked)\]\s+(.*)", line)
        if match:
            if current:
                items.append((state, clean_item(" ".join(current))))
            state = match.group(1)
            current = [match.group(2).strip()]
            continue
        if current and line.startswith("  ") and line.strip():
            current.append(line.strip())
            continue
        if current and not line.strip():
            items.append((state, clean_item(" ".join(current))))
            current = []
            state = ""
        if len(items) >= limit:
            break
    if current and len(items) < limit:
        items.append((state, clean_item(" ".join(current))))
    return items[:limit]


def dated_label(days: int) -> str:
    return (date.today() + timedelta(days=days)).isoformat()


def render_timeline_items(todo: str) -> str:
    items = active_items(todo, limit=16)
    now_items = [text for state, text in items if state in {"doing", "blocked"}][:4]
    if not now_items:
        now_items = [text for state, text in items if state == "next"][:3]
    next_items = [text for state, text in items if state == "next"][3:8]
    if not next_items:
        next_items = [text for state, text in items if state == "next"][:5]
    buckets = [
        (
            "Now",
            f"{dated_label(0)} to {dated_label(3)}",
            "Keep the UI compose path truthful and visible while closing regressions that block demos.",
            now_items,
        ),
        (
            "Next",
            f"{dated_label(4)} to {dated_label(10)}",
            "Turn the remaining high-value TODOs into repeatable device checks and public artifacts.",
            next_items,
        ),
        (
            "Then",
            f"{dated_label(11)} to {dated_label(21)}",
            "Use benchmark evidence to harden compatibility and publish tester-ready releases.",
            [
                "Close llama GPU bridge blockers without modifying llama.cpp.",
                "Stabilize container truth around Engine IDs, labels, health, logs, and ports.",
                "Promote verified templates and device reports into release notes and Wiki mirrors.",
            ],
        ),
    ]
    rows = []
    for phase, window, goal, phase_items in buckets:
        if not phase_items:
            phase_items = ["Refresh from TODO after the next implementation pass."]
        rows.append(f"### {phase}: {window}\n\n{goal}\n")
        rows.extend(f"- {item}" for item in phase_items)
        rows.append("")
    return "\n".join(rows).strip()


def load_library() -> dict:
    return json.loads(read_text(ROOT / "app/src/main/assets/project-library/library.json"))


def load_llama_compare() -> dict:
    path = ROOT / "docs/test/llama-gpu-compare-latest.json"
    if not path.exists():
        return {}
    return json.loads(read_text(path))


def status_table(library: dict) -> str:
    rows = []
    for template in library.get("templates", []):
        rows.append(
            "| {id} | {name} | {category} | {gpu} | {features} |".format(
                id=template.get("id", ""),
                name=template.get("name", ""),
                category=template.get("category", ""),
                gpu=template.get("gpu", ""),
                features=", ".join(template.get("features", [])[:5]),
            )
        )
    return "\n".join(rows)


def llama_section(llama: dict) -> str:
    if not llama:
        return "No llama GPU comparison artifact is recorded yet."
    comparison = llama.get("comparison", {})
    gpu = llama.get("gpu", {})
    diagnostics = gpu.get("diagnostics", {})
    policy = llama.get("policy", {})
    speedup = comparison.get("speedup", 0.0)
    target = comparison.get("target_met", False)
    blocker = llama.get("next_blocker") or diagnostics.get("blocker_detail") or "unknown"
    timestamp = llama.get("timestamp_utc", "unknown")
    entry = policy.get("gpu_entry", "unknown")
    return "\n".join(
        [
            f"- Latest artifact: `{timestamp}`",
            f"- GPU entry: {entry}",
            f"- Target met: `{str(target).lower()}`; speedup: `{speedup}`",
            f"- Current blocker: {blocker}",
            f"- llama.cpp modified: `{str(policy.get('llama_cpp_modified', False)).lower()}`",
        ]
    )


def render_dashboard() -> str:
    readme = read_text(ROOT / "README.md")
    status = read_text(ROOT / "docs/plan/STATUS.md")
    todo = read_text(ROOT / "docs/plan/TODO.md")
    compat = read_text(ROOT / "docs/test/compat-audit-latest.md")
    library = load_library()
    llama = load_llama_compare()
    counts = todo_counts(todo)
    items = active_items(todo)
    task_rows = "\n".join(f"| {state} | {text} |" for state, text in items)
    if not task_rows:
        task_rows = "| none | No active source item was found. |"
    return f"""# Showcase Dashboard

{GENERATED}

Source snapshot: `{snapshot_date(readme, status, todo, compat, json.dumps(llama))}`.
Repository reference: source-controlled generated snapshot.

This page is the GitHub-facing status board for pdocker-android. It is generated
from repository-owned documents so the public story follows the implementation
instead of drifting into a separate marketing copy.

## Product Signal

pdocker-android is a Docker-compatible Android workbench packaged as a native
APK. It combines `pdockerd`, Compose/Dockerfile controls, image/container file
browsing, persistent logs, editor tabs, and `-it`-style terminals inside the
app UI. The current research front is real Android direct execution plus
Vulkan/OpenCL GPU bridging for llama.cpp-class workloads.

## Live Counters

| Signal | Value |
|---|---:|
| Project-library templates | {len(library.get("templates", []))} |
| TODO done entries | {counts.get("done", 0)} |
| TODO doing entries | {counts.get("doing", 0)} |
| TODO next entries | {counts.get("next", 0)} |
| Compatibility audit PASS | {compat_count(compat, "PASS")} |
| Compatibility audit FAIL | {compat_count(compat, "FAIL")} |

## Workspaces To Show

| Template | Name | Category | GPU mode | Feature preview |
|---|---|---|---|---|
{status_table(library)}

## Active Queue

| State | Item |
|---|---|
{task_rows}

## Timeline

The live planning page is generated from [`docs/plan/TODO.md`](../plan/TODO.md)
with a small buffer over the recent implementation pace. Device builds, GPU
bridge work, and long Compose templates are expected to move slower than static
UI/docs work, so the public timeline is intentionally a little conservative.

- [Roadmap timeline](ROADMAP_TIMELINE.md)

## llama.cpp GPU Pulse

{llama_section(llama)}

## Demo Route

1. Start the APK and show the Overview cards rather than a host shell.
2. Run Compose up from the UI and keep the build log visible.
3. Open the container card, service URL, logs, files, and `-it` terminal.
4. Show the VS Code Server and llama.cpp templates as real project-library
   entries.
5. Finish with storage metrics, compatibility docs, and the current GPU
   blocker so viewers can tell what is working and what is research.

## Source Links

- [README](../../README.md)
- [Status](../plan/STATUS.md)
- [TODO](../plan/TODO.md)
- [Compatibility](../test/COMPATIBILITY.md)
- [Latest Compatibility Audit](../test/compat-audit-latest.md)
- [Promotion Kit](../manual/PROMOTION.md)
"""


def render_timeline() -> str:
    todo = read_text(ROOT / "docs/plan/TODO.md")
    status = read_text(ROOT / "docs/plan/STATUS.md")
    counts = todo_counts(todo)
    return f"""# Roadmap Timeline

{GENERATED}

Source snapshot: `{snapshot_date(todo, status)}`.
Repository reference: source-controlled generated snapshot.

This timeline is derived from the live TODO ledger and is meant for GitHub
issues, release planning, and Wiki readers. It is not a promise of fixed
release dates; it is a public operating plan that updates as implementation
evidence changes.

## Velocity Assumption

Recent development has closed many UI, direct-runtime, storage, template, and
test-ledger tasks in a short window. The public plan deliberately spends only
part of that apparent velocity because Android device builds, GPU bridges,
package-manager behavior, and long Compose templates have high variance.

Current TODO counters:

| State | Count |
|---|---:|
| done | {counts.get("done", 0)} |
| doing | {counts.get("doing", 0)} |
| next | {counts.get("next", 0)} |
| blocked | {counts.get("blocked", 0)} |

## Timeline

{render_timeline_items(todo)}

## Posting Rule

Use this page as the source for public roadmap posts:

- Pin the current `Now` and `Next` windows in a GitHub issue comment.
- Link back to `docs/plan/TODO.md` for the full ledger.
- When a milestone moves because of measured device behavior, update TODO
  first and regenerate this page.
- Keep optimistic claims out of the post until a repeatable test artifact
  exists under `docs/test/`.
"""


def render_wiki_home() -> str:
    library = load_library()
    return f"""# pdocker-android Wiki Home

{GENERATED}

This file is a source-controlled seed for the GitHub Wiki. Copy or sync it to
the Wiki `Home.md`; do not make the Wiki the only copy of product facts.

## Start Here

- Product overview: [README](../README.md)
- Showcase dashboard: [docs/showcase/PROJECT_DASHBOARD.md](PROJECT_DASHBOARD.md)
- Roadmap timeline: [docs/showcase/ROADMAP_TIMELINE.md](ROADMAP_TIMELINE.md)
- User manuals: [docs/manual/README.md](../manual/README.md)
- Architecture: [docs/design/README.md](../design/README.md)
- Build and test gates: [docs/build/README.md](../build/README.md),
  [docs/test/README.md](../test/README.md)
- Live plan: [docs/plan/TODO.md](../plan/TODO.md)

## Current Public Message

pdocker-android explores Docker-compatible workflows inside a normal Android
APK: Engine API behavior, Compose/Dockerfile UI, image/container files,
persistent logs, terminals, editor tabs, VS Code Server, llama.cpp, and
Android-specific GPU/media bridge work.

## Template Library

{chr(10).join(f"- `{t.get('id')}`: {t.get('name')}" for t in library.get("templates", []))}

## Wiki Sync Rule

The repository is the source of truth. Refresh this Wiki seed with:

```sh
python3 scripts/update-showcase.py
```

Then copy `docs/showcase/WIKI_HOME.md` into the GitHub Wiki, or let the
repository workflow publish it when Wiki automation is enabled.
"""


def render_showcase_index() -> str:
    return f"""# Showcase

{GENERATED}

This directory contains public-facing, GitHub-ready pages generated or curated
from the repository's canonical documentation.

| Page | Purpose |
|---|---|
| [PROJECT_DASHBOARD.md](PROJECT_DASHBOARD.md) | Generated status board for README, releases, and pinned issues |
| [ROADMAP_TIMELINE.md](ROADMAP_TIMELINE.md) | Generated TODO-linked roadmap for public updates |
| [NEWS_TIMELINE.md](NEWS_TIMELINE.md) | Curated public news and announcement timeline |
| [WIKI_HOME.md](WIKI_HOME.md) | Source-controlled seed for the GitHub Wiki home page |

The source of truth remains the repository itself: `README.md`, `docs/plan/`,
`docs/test/`, `docs/design/`, and the project-library templates.
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated files are stale")
    args = parser.parse_args()
    stale = False
    stale |= write_or_check(ROOT / "docs/showcase/README.md", render_showcase_index(), args.check)
    stale |= write_or_check(ROOT / "docs/showcase/PROJECT_DASHBOARD.md", render_dashboard(), args.check)
    stale |= write_or_check(ROOT / "docs/showcase/ROADMAP_TIMELINE.md", render_timeline(), args.check)
    stale |= write_or_check(ROOT / "docs/showcase/WIKI_HOME.md", render_wiki_home(), args.check)
    if stale and args.check:
        print("Run: python3 scripts/update-showcase.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
