#!/usr/bin/env python3
"""Offline checks for native UI action wiring.

This is not a substitute for device tapping, but it catches the common
"screen opens, then the useful action is disconnected" regressions:
Docker actions must open persistent PTY tools, image rows must deep-link to
the selected rootfs, and editor tabs must be keyed by file path.
"""

from __future__ import annotations

import sys
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MAIN = ROOT / "app/src/main/kotlin/io/github/ryo100794/pdocker/MainActivity.kt"
IMAGE = ROOT / "app/src/main/kotlin/io/github/ryo100794/pdocker/ImageFilesActivity.kt"
EDITOR = ROOT / "app/src/main/kotlin/io/github/ryo100794/pdocker/CodeEditorView.kt"
EDITOR_ACTIVITY = ROOT / "app/src/main/kotlin/io/github/ryo100794/pdocker/TextEditorActivity.kt"
XTERM = ROOT / "app/src/main/assets/xterm/index.html"
BRIDGE = ROOT / "app/src/main/kotlin/io/github/ryo100794/pdocker/Bridge.kt"
SAF_MEDIATOR = ROOT / "app/src/main/kotlin/io/github/ryo100794/pdocker/SafDocumentsMediator.kt"
PDOCKERD_BRIDGE = ROOT / "app/src/main/python/pdockerd_bridge.py"
ANDROID_SMOKE = ROOT / "scripts/android-device-smoke.sh"
STRINGS = [
    ROOT / "app/src/main/res/values/strings.xml",
    ROOT / "app/src/main/res/values-ja/strings.xml",
]


def ok(name: str) -> None:
    print(f"ok: {name}")


def fail(name: str) -> None:
    print(f"FAIL: {name}")
    raise SystemExit(1)


def require(name: str, condition: bool) -> None:
    ok(name) if condition else fail(name)


def main() -> int:
    main_src = MAIN.read_text()
    image_src = IMAGE.read_text()
    editor_src = EDITOR.read_text()
    editor_activity_src = EDITOR_ACTIVITY.read_text()
    xterm_src = XTERM.read_text()
    bridge_src = BRIDGE.read_text()
    saf_mediator_src = SAF_MEDIATOR.read_text()
    pdockerd_bridge_src = PDOCKERD_BRIDGE.read_text()
    pdockerd_src = (ROOT / "docker-proot-setup/bin/pdockerd").read_text()
    android_smoke_src = ANDROID_SMOKE.read_text() if ANDROID_SMOKE.exists() else ""
    api29_feasibility_src = (ROOT / "scripts/android-api29-direct-feasibility.sh").read_text()
    device_llama_template_src = (ROOT / "scripts/verify-device-llama-template.sh").read_text()
    llama_compare_src = (ROOT / "scripts/android-llama-gpu-compare.sh").read_text()
    vulkan_smoke_src = (ROOT / "scripts/smoke-vulkan-icd-bridge.sh").read_text()
    vulkan_llama_init_src = (ROOT / "scripts/smoke-vulkan-llama-init.sh").read_text()
    opencl_smoke_src = (ROOT / "scripts/smoke-opencl-bridge.sh").read_text()
    compat_audit_src = (ROOT / "scripts/compat-audit.py").read_text()
    verify_fast_src = (ROOT / "scripts/verify-fast.sh").read_text()
    bug_report_src = (ROOT / ".github/ISSUE_TEMPLATE/bug_report.yml").read_text()
    device_test_src = (ROOT / ".github/ISSUE_TEMPLATE/device_test.yml").read_text()
    gpu_executor_src = (ROOT / "app/src/main/cpp/pdocker_gpu_executor.c").read_text()
    vulkan_icd_src = (ROOT / "docker-proot-setup/src/gpu/pdocker_vulkan_icd.c").read_text()
    opencl_icd_src = (ROOT / "docker-proot-setup/src/gpu/pdocker_opencl_icd.c").read_text()
    llama_compose_src = (ROOT / "app/src/main/assets/project-library/llama-cpp-gpu/compose.yaml").read_text()
    llama_profile_src = (ROOT / "app/src/main/assets/project-library/llama-cpp-gpu/scripts/pdocker-gpu-profile.sh").read_text()
    manifest_src = (ROOT / "app/src/main/AndroidManifest.xml").read_text()
    debug_receiver_src = (ROOT / "app/src/main/kotlin/io/github/ryo100794/pdocker/PdockerdDebugReceiver.kt").read_text()
    engine_src = (ROOT / "app/src/main/kotlin/io/github/ryo100794/pdocker/DockerEngineClient.kt").read_text()
    ros2_rviz_compose = (ROOT / "app/src/main/assets/project-library/ros2-humble-rviz-novnc/compose.yaml").read_text()
    blender_compose = (ROOT / "app/src/main/assets/project-library/blender-xvnc-novnc/compose.yaml").read_text()
    docker_scope_src = (ROOT / "docs/design/DOCKER_COMPAT_SCOPE.md").read_text()
    cow_storage_src = (ROOT / "docs/design/COW_OVERLAY_STORAGE.md").read_text()
    metadata_index_src = (ROOT / "docs/design/PROJECT_METADATA_INDEX.md").read_text()
    default_workspace_src = (ROOT / "docs/manual/DEFAULT_DEV_WORKSPACE.md").read_text()
    string_src = "\n".join(path.read_text() for path in STRINGS)

    docker_action_count = main_src.count("openDockerTerminal(") - 1
    require("upstream docker cli is not a normal apk ui path", docker_action_count <= 1)
    require("default apk build targets process-exec compat flavor", 'PDOCKER_ANDROID_FLAVOR:=compat' in (ROOT / "scripts/build-apk.sh").read_text() and 'PDOCKER_ANDROID_FLAVOR:-compat' in android_smoke_src)
    require("fast audits default to compat apk flavor", 'FLAVOR_ENV = "PDOCKER_ANDROID_FLAVOR"' in compat_audit_src and 'os.environ.get(FLAVOR_ENV, "compat")' in compat_audit_src and 'PDOCKER_ANDROID_FLAVOR="${PDOCKER_ANDROID_FLAVOR:-compat}"' in verify_fast_src)
    require("fast apk flavor guard ignores stale modern artifacts", "APK_BY_FLAVOR" in compat_audit_src and 'APK = APK_BY_FLAVOR.get(FLAVOR)' in compat_audit_src and "app-debug.apk" not in compat_audit_src and "existing modern APK ignored by compat fast gate" in compat_audit_src)
    require("fast scripts reject unknown apk flavor", 'case "$PDOCKER_ANDROID_FLAVOR"' in verify_fast_src and 'case "$FLAVOR"' in android_smoke_src and "must be 'compat' or 'modern'" in verify_fast_src and "must be 'compat' or 'modern'" in android_smoke_src)
    require("public intake labels modern as metadata-only", "modern metadata-only" in bug_report_src and "modern metadata-only" in device_test_src)
    require("runtime flavors have distinct launcher labels", "pdocker compat" in (ROOT / "app/src/compat/res/values/strings.xml").read_text() and "pdocker modern" in (ROOT / "app/src/modern/res/values/strings.xml").read_text())
    build_gradle_src = (ROOT / "app/build.gradle.kts").read_text()
    gitignore_src = (ROOT / ".gitignore").read_text()
    require("main header surfaces version and build time", "appBuildInfo()" in main_src and "BUILD_TIME_UTC" in main_src and "app_build_info_fmt" in string_src and "buildConfigField(\"String\", \"BUILD_TIME_UTC\"" in build_gradle_src)
    manifest_src = (ROOT / "app/src/main/AndroidManifest.xml").read_text()
    require("app uses dedicated adaptive launcher icon", 'android:icon="@mipmap/ic_launcher"' in manifest_src and (ROOT / "app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml").exists() and (ROOT / "app/src/main/res/drawable/ic_launcher_foreground.xml").exists())
    require("gradle syncs pdockerd asset before apk packaging", "syncPdockerdAsset" in build_gradle_src and "docker-proot-setup/bin/pdockerd" in build_gradle_src and "merge" in build_gradle_src and "Assets" in build_gradle_src)
    require("gradle rejects stale native payloads before apk packaging", "verifyPackagedPayloadFresh" in build_gradle_src and "libpdockerdirect.so" in build_gradle_src and "pdocker_direct_exec.c" in build_gradle_src and "build-native-termux.sh" in build_gradle_src and "NativeLibs" in build_gradle_src)
    require("gradle rejects stale backend payloads before apk packaging", "libcrane.so" in build_gradle_src and "docker-bin/crane" in build_gradle_src and "libcow.so" in build_gradle_src and "copy-native.sh" in build_gradle_src and "requireSameBytes" in build_gradle_src)
    require("test-staged docker terminal helper remains diagnostic only", "private fun openDockerTerminal" in main_src and "startDaemon()" in main_src)
    require("diagnostic docker helper can wait for test-staged cli", "waiting for pdockerd" in main_src and "docker version >/dev/null" in main_src)
    require("docker build uses legacy builder env", "DOCKER_BUILDKIT=0" in main_src and "COMPOSE_DOCKER_CLI_BUILD=0" in main_src)
    require("terminal exports legacy builder env", "DOCKER_BUILDKIT=0" in bridge_src)
    require("compose up uses engine-native path", "runComposeUp" in main_src and "engine compose up" in main_src)
    require("apk setting configures shared documents volume env", "REQUEST_DOCUMENTS_TREE" in main_src and "ACTION_OPEN_DOCUMENT_TREE" in main_src and "takePersistableUriPermission" in main_src and "PDOCKER_DOCUMENTS_HOST" in main_src and "PDOCKER_DOCUMENTS_MOUNT" in main_src and "writeDocumentsEnv" in main_src and "syncDocumentsVolumeEnv" in main_src)
    require("documents folder is project workspace root", "documentsProjectsRoot()" in main_src and "documentsVolumeRootPath()" in main_src and "sharedDocumentsHostPath()" in main_src and "Project root" in string_src and "pdocker/projects" in default_workspace_src)
    require("documents project root falls back when sd path is not writable", "documentsProjectsRootWritable()" in main_src and "canWriteDirectoryByPath" in main_src and "legacyProjectRoot" in main_src)
    require("fresh install does not write public documents without saf grant", "if (uriText.isBlank()) return false" in main_src and "Android 13+ rejects" in main_src)
    require("documents storage classifies direct paths versus saf mediation", "PersistedDocumentsTreeMetadata" in main_src and "DocumentsWriteAccess" in main_src and "documentsTreeRequiresSafMediation" in main_src and "direct-path-writable" in main_src and "saf-mediated" in main_src and "probeDocumentsProjectsRootWritable" in main_src and "PDOCKER_DOCUMENTS_ACCESS" in main_src and "PDOCKER_DOCUMENTS_DIRECT_HOST" in main_src and "PDOCKER_DOCUMENTS_MEDIATED_HOST" in main_src and "PDOCKER_DOCUMENTS_MEDIATOR" in main_src and "host_environment_documents_fmt" in string_src and "DocumentProvider" in docker_scope_src and "saf-mediated" in default_workspace_src)
    require("saf documents mediator exposes minimal document api", "class SafDocumentsMediator" in saf_mediator_src and "takePersistableUriPermission" in main_src and "DocumentsContract.createDocument" in saf_mediator_src and "buildChildDocumentsUriUsingTree" in saf_mediator_src and "openInputStream" in saf_mediator_src and "openOutputStream" in saf_mediator_src and "fun ensureDirectory" in saf_mediator_src and "fun list" in saf_mediator_src and "fun exists" in saf_mediator_src and "fun writeBytes" in saf_mediator_src and "fun readBytes" in saf_mediator_src and "PDOCKER_DOCUMENTS_SAF_MIRROR_HOST" in main_src and "PDOCKER_DOCUMENTS_SAF_SIDECAR_HOST" in main_src)
    require("saf documents mediator has explicit sync api and ui actions", "fun syncToTree" in saf_mediator_src and "fun syncFromTree" in saf_mediator_src and "fun statusJson" in saf_mediator_src and "runDocumentsMediatorAction" in main_src and "action_documents_sync_to_tree" in main_src and "action_documents_sync_from_tree" in main_src and "/system/documents/status" in main_src and "/system/documents/sync-to-tree" in main_src and "/system/documents/sync-from-tree" in main_src and "collect_documents_environment" in pdockerd_src and 'path == "/system/documents/status"' in pdockerd_src and 'path == "/system/documents/sync-to-tree"' in pdockerd_src and 'path == "/system/documents/sync-from-tree"' in pdockerd_src)
    require("saf mediated mirror buffers near-real-time writes", "FileObserver" in main_src and "startDocumentsMirrorSync" in main_src and "pendingDocumentsSyncPaths" in main_src and "DOCUMENTS_SYNC_DEBOUNCE_MS" in main_src and "syncPathToTree" in saf_mediator_src and "scheduleDocumentsSyncToTree(job)" in main_src)
    require("saf mediated mirror has scan fallback for new directories", "documentsMirrorScanTask" in main_src and "scanDocumentsExportMirrorForChanges" in main_src and "MAX_DOCUMENTS_SYNC_SCAN_ENTRIES" in main_src and '"pdocker-exports"' in main_src)
    require("saf sidecar records unix-like metadata", '"unixMetadata"' in saf_mediator_src and '"sidecar"' in saf_mediator_src and '"mode"' in saf_mediator_src and '"modifiedAt"' in saf_mediator_src and "recordDirectorySidecar" in saf_mediator_src and "unixMode" in saf_mediator_src)
    require("saf synced export payloads are evicted from app mirror", "evictMirrorPayload = true" in main_src and "evictableMirrorPayload" in saf_mediator_src and '"saf-synced-mirror-evicted"' in saf_mediator_src and '"EvictedMirrorFiles"' in saf_mediator_src and '"payloadState"' in saf_mediator_src)
    sync_to_tree_src = re.split(r"fun\s+syncToTree\s*\(", saf_mediator_src, maxsplit=1)[1]
    sync_to_tree_src = re.split(r"fun\s+syncFromTree\s*\(", sync_to_tree_src, maxsplit=1)[0]
    require("saf sync-to-tree streams files instead of readBytes", "copyFileToTree" in sync_to_tree_src and ".readBytes()" not in sync_to_tree_src and "copyCountingTo" in saf_mediator_src)
    sync_from_tree_src = re.split(r"fun\s+syncFromTree\s*\(", saf_mediator_src, maxsplit=1)[1].split("fun exists", 1)[0]
    require("saf sync-from-tree streams files instead of readBytes", "copyFileFromTree" in sync_from_tree_src and ".readBytes()" not in sync_from_tree_src and "openInputStream" in saf_mediator_src and "target.outputStream()" in saf_mediator_src and "copyCountingTo" in saf_mediator_src)
    require("saf sync-from-tree reports source counts from tree", "sourceFiles += 1" in sync_from_tree_src and "sourceBytes +=" in sync_from_tree_src and "sourceFiles = sourceFiles" in sync_from_tree_src and "sourceBytes = sourceBytes" in sync_from_tree_src)
    require("saf sync report surfaces source counts success and errors", '"Success"' in saf_mediator_src and '"SourceExists"' in saf_mediator_src and '"SourceFiles"' in saf_mediator_src and '"SourceBytes"' in saf_mediator_src and '"Files"' in saf_mediator_src and '"Directories"' in saf_mediator_src and '"Errors"' in saf_mediator_src and "errorJson" in saf_mediator_src)
    require("saf write failures are reported for ui json", "CopyResult(false" in saf_mediator_src and '"openOutputStream returned null"' in saf_mediator_src and "errors.put(errorJson" in saf_mediator_src)
    require("documents status exposes persisted grant and access mode", "persistedGrantState" in saf_mediator_src and '"PersistedReadGrant"' in saf_mediator_src and '"PersistedWriteGrant"' in saf_mediator_src and '"PersistedGrantAvailable"' in main_src and '"Mode"' in main_src and '"Access"' in main_src and "documentsGrantStatusLabel" in main_src and "grant %5$s" in string_src)
    require("sync to saf wording clarifies mediated mirror scope", "Usually unnecessary when storage access is direct-path writable" in string_src and "direct-path 書き込み可の場合は通常不要" in string_src)
    require("docs define sd card metadata sidecar limits", "FAT32 or exFAT" in cow_storage_src and "app-private metadata" in cow_storage_src and "DocumentProvider" in cow_storage_src and "direct POSIX writes" in cow_storage_src and "conflict state" in metadata_index_src and "archive/copy/import/export semantics only" in metadata_index_src and "FAT32 or exFAT" in default_workspace_src)
    require("documents env supports per-container and cross-project sharing", "PDOCKER_PROJECT_VOLUME_HOST" in main_src and "PDOCKER_SHARED_DOCUMENTS_HOST" in main_src and "PDOCKER_FAST_WORKSPACE_HOST" in main_src)
    require("existing compose files migrate documents mounts", "migrateComposeDocuments" in main_src and "PDOCKER_SHARED_DOCUMENTS_HOST" in main_src and "PDOCKER_MODEL_HOST:-./models" in main_src)
    require("installed project compose files migrate on startup", "migrateInstalledProjects()" in main_src and "override fun onResume()" in main_src and "projectDirs().forEach" in main_src and "migrateProjectPorts(project)" in main_src)
    require("llama template migration removes stale shader wrapper tuning", "migrateLlamaCppGpuWorkspace(project)" in main_src and "LLAMA_CPP_VULKAN_SHADER_PROFILE" in main_src and "pdocker-bridge-safe-glslc" in main_src and "git checkout --detach FETCH_HEAD" in main_src and ".pdocker-template-backups/llama-cpp-gpu-" in main_src)
    require("llama template migration installs KV offload guard", "PDOCKER_VULKAN_ALLOW_KV_OFFLOAD" in main_src and "--no-kv-offload" in main_src and ".pdocker-template-version\").writeText(\"11" in main_src)
    require("llama template defaults to validated one-layer Vulkan offload", "LLAMA_ARG_N_GPU_LAYERS: \"${LLAMA_ARG_N_GPU_LAYERS:-1}\"" in llama_compose_src and "LLAMA_ARG_N_GPU_LAYERS:-2" not in llama_compose_src and "staleGpuLayerDefault" in main_src)
    require("llama template defaults to measured pipeline optimization path", "PDOCKER_GPU_DISABLE_PIPELINE_OPTIMIZATION: \"${PDOCKER_GPU_DISABLE_PIPELINE_OPTIMIZATION:-0}\"" in llama_compose_src and "stalePipelineOptimizationDefault" in main_src)
    require("device llama template verifier catches app-data update drift", "LLAMA_CPP_VULKAN_SHADER_PROFILE" in device_llama_template_src and "git checkout --detach FETCH_HEAD" in device_llama_template_src and "LLAMA_CPP_BUILD_JOBS:-1" in device_llama_template_src and "LLAMA_CPP_BUILD_TYPE:-Release" in device_llama_template_src and "PDOCKER_VULKAN_ALLOW_KV_OFFLOAD" in device_llama_template_src and "--no-kv-offload" in device_llama_template_src)
    require("documents volume requests legacy storage permission when useful", "READ_EXTERNAL_STORAGE" in manifest_src and "WRITE_EXTERNAL_STORAGE" in manifest_src and "REQUEST_EXTERNAL_STORAGE" in main_src)
    require("compose parser expands project env for documents volume", "composeEnvironment(dir)" in main_src and "File(projectDir, \".env\")" in main_src and "File(projectRoot, \".pdocker-common.env\")" in main_src and "composeValue(value, composeEnv)" in main_src)
    require("legacy docker-compose normalizer remains test-only", "normalizeDockerCommand" in main_src and "docker-compose" in main_src and "docker compose" in main_src)
    runtime_src = (ROOT / "app/src/main/kotlin/io/github/ryo100794/pdocker/PdockerdRuntime.kt").read_text()
    pdockerd_src = (ROOT / "docker-proot-setup/bin/pdockerd").read_text()
    direct_src = (ROOT / "app/src/main/cpp/pdocker_direct_exec.c").read_text()
    require("runtime omits upstream docker cli and compose plugin", "libdocker.so" not in runtime_src and "libdocker-compose.so" not in runtime_src and 'File(dockerBin, "docker")' in runtime_src)
    require("runtime installs direct executor helper", "libpdockerdirect.so" in runtime_src and "pdocker-direct" in runtime_src and "PDOCKER_DIRECT_EXECUTOR" in pdockerd_bridge_src)
    require("runtime installs backend-neutral gpu executor helper", "libpdockergpuexecutor.so" in runtime_src and "pdocker-gpu-executor" in runtime_src and "PDOCKER_GPU_COMMAND_API" in pdockerd_bridge_src and "PDOCKER_GPU_LLM_ENGINE_LOCATION" in pdockerd_src)
    require("runtime installs media executor control socket helper", "libpdockermediaexecutor.so" in runtime_src and "pdocker-media-executor" in runtime_src and "PDOCKER_MEDIA_COMMAND_API" in pdockerd_bridge_src and "PDOCKER_MEDIA_DEVICE_PASSTHROUGH" in pdockerd_bridge_src)
    require("runtime installs glibc gpu shim for containers", "libpdockergpushim.so" in runtime_src and "pdocker-gpu-shim" in runtime_src and "PDOCKER_GPU_SHIM_HOST_PATH" in pdockerd_bridge_src and "PDOCKER_GPU_SHIM" in pdockerd_src)
    require("runtime installs glibc Vulkan ICD for containers", "libpdockervulkanicd.so" in runtime_src and "pdocker-vulkan-icd.so" in runtime_src and "PDOCKER_VULKAN_ICD_HOST_PATH" in pdockerd_bridge_src and "PDOCKER_VULKAN_ICD_KIND" in pdockerd_bridge_src and "PDOCKER_VULKAN_ICD" in pdockerd_src and "/usr/local/lib/pdocker-vulkan-icd.so" in pdockerd_src)
    require("vulkan icd bridge has reusable smoke test", "VK_ICD_FILENAMES" in vulkan_smoke_src and "vkQueueSubmit" in vulkan_smoke_src and "PDOCKER_GPU_QUEUE_SOCKET" in vulkan_smoke_src)
    require("vulkan icd exposes maintenance4 large-buffer diagnostics", "VkPhysicalDeviceMaintenance4Features" in vulkan_icd_src and "maintenance4 = VK_TRUE" in vulkan_icd_src and "create-buffer size=" in vulkan_icd_src and "buffer-requirements size=" in vulkan_icd_src and "minStorageBufferOffsetAlignment = 16" in vulkan_icd_src)
    require("vulkan icd advertises fragile features conservatively", "PDOCKER_VULKAN_ENABLE_INT64" in vulkan_icd_src and "PDOCKER_VULKAN_ENABLE_SUBGROUP_ARITHMETIC" in vulkan_icd_src and "PDOCKER_VULKAN_ENABLE_16BIT_STORAGE" in vulkan_icd_src and "shaderInt64 must be opt-in" in vulkan_llama_init_src and "BASIC only" in vulkan_llama_init_src)
    require("vulkan icd lets transfer-only submits complete and forwards compute", "has_dispatch" in vulkan_icd_src and "queue-submit transfer-only command buffer" in vulkan_icd_src and "send_generic_vulkan_dispatch" in vulkan_icd_src and "VULKAN_DISPATCH_V2" in vulkan_icd_src and "VULKAN_DISPATCH_V2" in gpu_executor_src and "VULKAN_DISPATCH_V1" in gpu_executor_src)
    require("vulkan icd has opt-in copy alias fast path", "PDOCKER_VULKAN_ALIAS_COPIES" in vulkan_icd_src and "descriptor alias binding" in vulkan_icd_src and "copy-alias" in vulkan_icd_src and "PDOCKER_VULKAN_ALIAS_COPIES=1" in (ROOT / "scripts/android-llama-gpu-compare.sh").read_text())
    require("gpu executor supports default duplicate descriptor aliasing", "PDOCKER_GPU_REWRITE_DUPLICATE_DESCRIPTOR_BINDINGS" in gpu_executor_src and "env_truthy(\"PDOCKER_GPU_REWRITE_DUPLICATE_DESCRIPTOR_BINDINGS\", 1)" in gpu_executor_src and "rewrite_duplicate_descriptor_bindings" in gpu_executor_src and "PDOCKER_GPU_REWRITE_DUPLICATE_DESCRIPTOR_BINDINGS" in pdockerd_src)
    require("gpu executor disables fragile driver pipeline optimization by default", "PDOCKER_GPU_DISABLE_PIPELINE_OPTIMIZATION" in gpu_executor_src and "VK_PIPELINE_CREATE_DISABLE_OPTIMIZATION_BIT" in gpu_executor_src and "PDOCKER_GPU_DISABLE_PIPELINE_OPTIMIZATION" in pdockerd_src)
    require("runtime installs glibc OpenCL ICD for containers", "libpdockeropenclicd.so" in runtime_src and "pdocker-opencl-icd.so" in runtime_src and "libOpenCL.so.1" in runtime_src and "PDOCKER_OPENCL_ICD_HOST_PATH" in pdockerd_bridge_src and "PDOCKER_OPENCL_ICD" in pdockerd_src and "/usr/local/lib/pdocker-opencl-icd.so" in pdockerd_src)
    require("opencl bridge has reusable smoke test", "clEnqueueNDRangeKernel" in opencl_smoke_src and "PDOCKER_GPU_QUEUE_SOCKET" in opencl_smoke_src and "pdocker-opencl-icd.so" in opencl_smoke_src)
    require("gpu executor attempts Android OpenCL before GLES fallback", "dlopen" in gpu_executor_src and "android_opencl" in gpu_executor_src and "falling back to GLES compute" in gpu_executor_src)
    require("gpu executor has Android Vulkan same-api probe", "android_vulkan" in gpu_executor_src and "--bench-vulkan-vector-add" in gpu_executor_src and "backend_affinity_policy" in gpu_executor_src and "--bench-vulkan-vector-add" in android_smoke_src)
    require("gpu executor caches repeated Vulkan pipelines", "PDOCKER_GPU_PIPELINE_CACHE_SLOTS" in gpu_executor_src and "pipeline_cache" in gpu_executor_src and "find_pipeline_cache_entry" in gpu_executor_src)
    require("gpu executor reuses mutable Vulkan buffers", "PDOCKER_GPU_MUTABLE_BUFFER_CACHE_SLOTS" in gpu_executor_src and "mutable_buffer_cache" in gpu_executor_src and "find_mutable_buffer_cache_entry" in gpu_executor_src)
    require("opencl icd refuses unsupported kernels", "trace_unsupported_kernel" in opencl_icd_src and "kernel_is_supported_vector_add" in opencl_icd_src and "CL_INVALID_OPERATION" in opencl_icd_src)
    require("opencl icd covers common object and buffer APIs", "clGetKernelWorkGroupInfo" in opencl_icd_src and "clEnqueueFillBuffer" in opencl_icd_src and "clEnqueueMapBuffer" in opencl_icd_src and "clGetProgramInfo" in opencl_icd_src)
    require("llama profile distinguishes ready OpenCL bridge from llama backend", "pdocker_opencl_icd_ready_signal" in llama_profile_src and "llama.cpp OpenCL kernel lowering is not complete yet" in llama_profile_src and "PDOCKER_OPENCL_API_VERSION" in llama_profile_src)
    require("pdockerd exposes bounded host environment diagnostics", 'path == "/system/host"' in pdockerd_src and "collect_host_environment" in pdockerd_src and '"Frameworks"' in pdockerd_src and '"OpenCL"' in pdockerd_src and '"NnApi"' in pdockerd_src and '"OpenCVPython"' not in pdockerd_src and '"PATH"' not in pdockerd_src.split("def collect_host_environment", 1)[1].split("def _direct_rootfs_path", 1)[0])
    require("ui renders host environment pane from engine api", "renderHostEnvironment()" in main_src and 'engine.getObject("/system/host")' in main_src and "widget_host_environment" in string_src and "host_environment_gpu_fmt" in string_src and "host_environment_vulkan_fmt" in string_src and "host_environment_opencl_fmt" in string_src and "host_environment_accel_fmt" in string_src)
    service_src = (ROOT / "app/src/main/kotlin/io/github/ryo100794/pdocker/PdockerdService.kt").read_text()
    require("pdockerd service starts gpu executor socket", "--serve-socket" in service_src and "pdocker-gpu.sock" in service_src and "gpuExecutorProcess" in service_src and "PDOCKER_GPU_QUEUE_SOCKET" in pdockerd_bridge_src)
    require("pdockerd service starts media executor socket without capture readiness", "--serve-socket" in service_src and "pdocker-media.sock" in service_src and "--descriptor" in service_src and "mediaExecutorProcess" in service_src and "PDOCKER_MEDIA_CAPTURE_READY" in pdockerd_bridge_src)
    require("direct runtime advertises implemented bind support", "PDOCKER_USE_COW_BIND" in pdockerd_bridge_src and 'if DIRECT_EXECUTOR and os.path.exists(DIRECT_EXECUTOR)' in pdockerd_src and '"cow-bind=1" in output' in pdockerd_src and "cow-bind=0" in direct_src and "bind-path-rewrite=1" in direct_src)
    require("direct runtime rewrites unix socket paths", "rewrite_unix_sockaddr_arg" in direct_src and "AF_UNIX" in direct_src and "case 200" in direct_src and "case 203" in direct_src and "ADD_TRACE_SYSCALL(200)" in direct_src and "ADD_TRACE_SYSCALL(203)" in direct_src and "/run/pdocker-gpu" in pdockerd_bridge_src)
    require("direct runtime suppresses noisy nscd socket rewrites", "should_skip_unix_socket_rewrite" in direct_src and "/var/run/nscd/socket" in direct_src and "/run/nscd/socket" in direct_src)
    require("direct runtime treats blocked NUMA policy syscalls as unavailable", "case 235: return \"mbind\"" in direct_src and "syscall_emulate_errno" in direct_src and "ADD_ERRNO_SYSCALL(235, ENOSYS)" in direct_src and "set_mempolicy_home_node" in direct_src)
    require("runtime removes stale docker-compose shim", "docker-compose" in runtime_src)
    require("runtime selects no-proot when proot absent", 'PDOCKER_RUNTIME_BACKEND", "no-proot"' in pdockerd_bridge_src)
    require("terminal exposes test cli config path without bundling cli", "DOCKER_CONFIG=${runtime.absolutePath}/docker-bin" in bridge_src and "Product APKs do not bundle upstream Docker CLI" in bridge_src)
    require("docker helper keeps absolute test cli config", 'File(filesDir, "pdocker-runtime/docker-bin").absolutePath' in main_src and 'DOCKER_CONFIG=$dockerConfig' in main_src)
    require("one-shot docker commands leave an interactive shell", "status=\\$?" in main_src and "exec sh" in main_src)
    require("docker actions create native job cards", "private data class DockerJob" in main_src and "renderDockerJobs" in main_src)
    require("docker jobs persist state to json", "jobs.json" in main_src and "saveDockerJobs()" in main_src)
    require("docker jobs persist full log files", "logs/jobs/$jobId.log" in main_src and "appendPersistentJobLog" in main_src and "readJobLogText" in main_src)
    require("docker jobs capture terminal output", "onOutput: ((ByteArray) -> Unit)?" in main_src and "handleDockerJobOutput" in main_src)
    require("docker jobs record exit markers", "__PDOCKER_JOB_EXIT" in main_src and "job_status_failed_fmt" in string_src)
    require("docker jobs parse progress lines", "dockerJobProgressLine" in main_src and "snapshotting layer:" in main_src and "Successfully tagged" in main_src)
    require("docker jobs render logs through xterm", "TerminalLogPane" in main_src and "TerminalLogBridge" in (ROOT / "app/src/main/kotlin/io/github/ryo100794/pdocker/TerminalLogBridge.kt").read_text() and "terminalLogPane()" in main_src and "ToolKind.Terminal" in main_src)
    require("log panes are readonly and do not summon keyboard", "fun readOnly(): Boolean = true" in (ROOT / "app/src/main/kotlin/io/github/ryo100794/pdocker/TerminalLogBridge.kt").read_text() and "body.readonly-log #keybar" in xterm_src and "term.options.disableStdin = true" in xterm_src and "inputmode', 'none'" in xterm_src and "if (!readOnly)" in xterm_src)
    require("readonly log terminals use compact font", "const initialFontSize = readOnly ? 8 : 12" in xterm_src and "let fontSize = initialFontSize" in xterm_src and "clamp(Math.round(value * 10) / 10, 8, 24)" in xterm_src)
    require("docker jobs preserve carriage-return progress", "terminalDisplayText" in main_src and "recordJobTerminalOutput" in main_src and "text.endsWith(\"\\r\")" in main_src and "replace(\"\\r\", \"\")" not in main_src)
    require("engine job logs render terminal CRLF", "normalizeTerminalNewlines" in main_src and "\"$text\\r\\n\"" in main_src and "ch == '\\n' && previous != '\\r'" in main_src)
    require("job summaries tick while logs are quiet", "jobTickerTask" in main_src and "tickRunningJobs" in main_src and "job_activity_fmt" in string_src)
    require("job log ui batches expensive refreshes", "scheduleDockerJobsSave" in main_src and "scheduleJobRenderUpdate" in main_src and "postDelayed" in main_src and "terminalDisplayText" in main_src)
    require("activity rotation ignores sensors", 'android:screenOrientation="nosensor"' in manifest_src and "SCREEN_ORIENTATION_NOSENSOR" in main_src)
    require("notification permission is user-initiated", "requestNotificationPermission()" not in main_src.split("override fun onCreate", 1)[1].split("override fun onNewIntent", 1)[0] and "action_enable_notifications" in string_src)
    require("engine stream keeps terminal control characters", "decoded.split('\\n')" in engine_src and "decoded.replace(\"\\r\", \"\")" not in engine_src)
    require("engine progress clears terminal line", '"\\r\\u001B[2K$progressLine\\r"' in engine_src)
    require("dockerfile RUN streams output before process exit", "subprocess.Popen" in pdockerd_src and "read1" in pdockerd_src and "emit(chunk.decode" in pdockerd_src)
    require("docker build context streams to temp file", "_read_body_to_temp" in pdockerd_src and "pdbuildctx_" in pdockerd_src and "tarfile.open(context_tar_path" in pdockerd_src and "BytesIO(context_tar)" not in pdockerd_src)
    require("large engine request bodies stream to temp files", "pdloadbody_" in pdockerd_src and "open(body_path, \"rb\")" in pdockerd_src and "pdarchiveput_" in pdockerd_src and "tarfile.open(body_path" in pdockerd_src and "BytesIO(body)" not in pdockerd_src)
    require("docker save response spools to temp file", "pdsavebody_" in pdockerd_src and "save_images(names, out)" in pdockerd_src and "os.path.getsize(save_path)" in pdockerd_src and "inp.read(1024 * 1024)" in pdockerd_src and "buf.getvalue()" not in pdockerd_src)
    require("pdockerd records python memory telemetry", "PYTHON_MEMORY_DIAGNOSTICS_PATH" in pdockerd_src and "_route_with_memory_trace" in pdockerd_src and "_self_python_memory_snapshot" in pdockerd_src and "gc.get_count()" in pdockerd_src and "PDOCKER_PYTHON_MEMORY_MIN_DELTA_KB" in pdockerd_src and "/system/python-memory" in pdockerd_src)
    require("build prune deletes unreferenced layers", "prune_unreferenced_layers" in pdockerd_src and "referenced_layer_ids" in pdockerd_src and '"LayersDeleted"' in pdockerd_src)
    require("android rebuilds prune stale layers automatically", "PDOCKER_AUTO_PRUNE_UNREFERENCED_LAYERS" in pdockerd_bridge_src and "prune-unreferenced-layers" in pdockerd_src)
    require("build rootfs prune skips active builds and runs on daemon startup", "PDOCKER_AUTO_PRUNE_BUILD_ARTIFACTS" in pdockerd_bridge_src and "def _path_referenced_by_process" in pdockerd_src and "build prune skipped active" in pdockerd_src and "auto-pruned stale build artifacts" in pdockerd_src)
    require("dockerfile RUN layers are cached by parent stack", "build_cache_key" in pdockerd_src and "Using cache sha256" in pdockerd_src and "store_build_cache_entry" in pdockerd_src)
    require("build layers do not cache stale absolute symlink marker", '".pdocker-absolute-symlinks-normalized"' in pdockerd_src and "os.remove(os.path.join(dst_rootfs, \".pdocker-absolute-symlinks-normalized\"))" in pdockerd_src and "_BUILD_SKIP" in pdockerd_src)
    require("existing image tags seed first rebuild cache", "prior_tag_layer" in pdockerd_src and "Using inline cache" in pdockerd_src and "inline-tag" in pdockerd_src)
    require("unchanged dockerfiles can skip full image rebuild", "try_reuse_existing_tag" in pdockerd_src and "Using image cache" in pdockerd_src and "file_equal" in pdockerd_src)
    require("container stop reconciles orphan runtime pid", "_pid_alive" in pdockerd_src and "_signal_pid_group" in pdockerd_src and 'state["State"]["Pid"] = 0' in pdockerd_src)
    require("container runtime state tracks pid identity", "_pid_start_time" in pdockerd_src and "PidStartTime" in pdockerd_src and "_docker_exit_code" in pdockerd_src)
    require("container runtime tracks reparented workload pid set", "PdockerLauncherPid" in pdockerd_src and "PdockerKnownPids" in pdockerd_src and "_start_container_process_tracker" in pdockerd_src and "_refresh_container_process_snapshot" in pdockerd_src)
    require("container raw return code remains diagnosable", "PdockerRawReturnCode" in pdockerd_src and "PdockerSignal" in pdockerd_src and "PdockerLastPid" in pdockerd_src and "_record_container_return_code" in pdockerd_src)
    require("engine exec allocates tty pty", "os.forkpty()" in pdockerd_src and "class ForkPtyProcess" in pdockerd_src and "stdin_fd = os.dup(master_fd)" in pdockerd_src and "self.stdin = os.fdopen(stdin_fd" in pdockerd_src)
    require("engine exec pty owns controlling terminal and sane enter mode", "os.forkpty()" in pdockerd_src and "termios.ICRNL" in pdockerd_src and "termios.ICANON" in pdockerd_src and "os.execvpe(argv[0], argv" in pdockerd_src)
    require("engine exec supports android python without forkpty", "class OpenPtyProcess" in pdockerd_src and "pty.openpty()" in pdockerd_src and "open_unix98_pty" in pdockerd_src and 'os.open("/dev/ptmx"' in pdockerd_src and "termios.TIOCSCTTY" in pdockerd_src and "preexec_fn=child_tty_setup" in pdockerd_src)
    require("engine exec supports docker-compatible tty resize", "^/exec/(.+?)/resize$" in pdockerd_src and "TIOCSWINSZ" in pdockerd_src and "SIGWINCH" in pdockerd_src and "resizeEngineExecSync" in bridge_src and "/resize?h=$rows&w=$cols" in bridge_src)
    require("engine exec tty output preserves raw pty bytes", "def tty_output(chunk)" in pdockerd_src and "_pdocker_raw_pty" in pdockerd_src and 'return chunk' in pdockerd_src and "_pdocker_tty_prev_cr" in pdockerd_src and "did not preserve terminal CRLF line control" in main_src)
    require("engine exec tty ctrl-c forwards to traced foreground process", "_pdocker_tty_like = True" in pdockerd_src and 'b"\\x03" in chunk' in pdockerd_src and "_signal_descendant_groups(proc.pid, signal.SIGINT)" in pdockerd_src and "os.killpg(pgid, sig)" in pdockerd_src)
    require("direct executor puts tracee in foreground pgrp for tty", "#include <termios.h>" in direct_src and "tcsetpgrp(STDIN_FILENO, child)" in direct_src)
    require("direct executor maps container dev tty to tty stdin", 'strcmp(guest, "/dev/tty") == 0' in direct_src and '"/proc/self/fd/0"' in direct_src and "isatty(STDIN_FILENO)" in direct_src)
    require("direct executor maps container proc to synthetic proc", "ensure_synthetic_proc_files" in pdockerd_src and '"meminfo"' in pdockerd_src and "pdocker-init" in pdockerd_src and 'strcmp(guest, "/proc") == 0' in direct_src and 'strncmp(guest, "/proc/", 6) == 0' in direct_src and '.pdocker-proc%s' in direct_src)
    require("engine exec it falls back when pty is unavailable", "pty unavailable for exec" in pdockerd_src and "falling back to pipes" in pdockerd_src and "stderr=subprocess.STDOUT" in pdockerd_src)
    require("engine exec pipe fallback maps terminal enter", "_pdocker_pipe_tty_fallback" in pdockerd_src and 'replace(b"\\r", b"\\n")' in pdockerd_src)
    require("engine exec stdin pump uses buffered hijack stream", 'getattr(self.rfile, "read1", None)' in pdockerd_src and "self.connection.recv(4096)" not in pdockerd_src)
    require("direct executor getcwd reads tracee cwd", '"/proc/%d/cwd"' in direct_src and "readlink(proc_cwd" in direct_src)
    require("direct executor resolves initial argv from rootfs path", "resolve_guest_program(rootfs, cmd0, target" in direct_src and 'getenv("PATH")' not in direct_src)
    require("direct build run revalidates absolute symlinks", 'strcmp(mode, "build") == 0' in direct_src and 'PDOCKER_DIRECT_NORMALIZE_SYMLINKS' in direct_src and '"always"' in direct_src)
    require("direct executor preserves shell bracket and long argv rewrite", "guest_exec_path" in direct_src and "copied_arg_ptrs" in direct_src and "old_argv0" in direct_src and "ExecArgArena copied_arg_arena" in direct_src and "read_tracee_string_to_arena" in direct_src and "char (*copied_arg_values)[PATH_MAX]" not in direct_src and "pdocker-bracket-ok" in android_smoke_src and "pdocker-long-argv-ok" in android_smoke_src and "flash_attn.comp.cpp.o" in android_smoke_src and '/usr/bin/[ \\"x\\" = \\"x\\" ]' in android_smoke_src)
    require("engine api jobs are persisted", "runEngineJob" in main_src and "appendEngineJobOutput" in main_src and "finishEngineJob" in main_src)
    require("engine api jobs open fresh result tabs", 'val key = "engine-job:$jobId:$group:$title"' in main_src and 'val jobId = "job-" + System.currentTimeMillis().toString(36)' in main_src)
    require("engine api jobs refresh container truth after completion", "refreshContainerSnapshotAsync(force = true)" in main_src.split("private fun runEngineJob", 1)[1].split("private fun summarizeEngineFailure", 1)[0])
    require("streaming engine failures summarize instead of replaying full logs", "summarizeEngineFailure" in main_src and "finishOutput" in main_src and "No space left" in main_src)
    require("engine jobs wait through slow daemon warmup", "private fun waitForEngine(timeoutMs: Long = 90_000)" in main_src)
    require("main activity restarts missing daemon", "ensureDaemonStarted" in main_src and "lastDaemonStartAttemptAt" in main_src and "pdockerd.sock" in main_src)
    service_src = (ROOT / "app/src/main/kotlin/io/github/ryo100794/pdocker/PdockerdService.kt").read_text()
    require("pdockerd service strongly restarts unless user stopped", "START_STICKY" in service_src and "onTaskRemoved" in service_src and "setExactAndAllowWhileIdle" in service_src and "holdStartWakeLock" in service_src and "if (!stopFlag && !userStopped)" in service_src)
    require("ui binds pdockerd as important during foreground builds", "LocalBinder : Binder" in service_src and "override fun onBind(intent: Intent?): IBinder = binder" in service_src and "ServiceConnection" in main_src and "BIND_IMPORTANT" in main_src and "bindPdockerdService()" in main_src)
    require("pdockerd service is isolated from ui crashes", 'android:process=":pdockerd"' in manifest_src)
    require("background daemon receivers avoid waking ui process", 'android:name=".PdockerdBootReceiver"' in manifest_src and 'android:name=".PdockerdDebugReceiver"' in manifest_src and manifest_src.count('android:process=":pdockerd"') >= 3)
    if "override fun onCreate()" in service_src:
        service_on_create = service_src.split("override fun onCreate()", 1)[1].split("override fun onStartCommand", 1)[0]
    else:
        service_on_create = ""
    service_start = service_src.split("private fun startPdockerd()", 1)[1].split("private fun startGpuExecutor", 1)[0]
    require("pdockerd service keeps heavy startup off lifecycle main thread", "Python.start" not in service_on_create and "PdockerdRuntime.prepare" not in service_on_create and "Thread({" in service_start and "PdockerdRuntime.prepare(appContext)" in service_start and "Python.start(AndroidPlatform(appContext))" in service_start)
    require("debug broadcast probes are bounded", "waitFor(10, TimeUnit.SECONDS)" in debug_receiver_src and "destroyForcibly()" in debug_receiver_src and "firstRootfs" in debug_receiver_src and "visited < 512" in debug_receiver_src)
    require("ui file walks are bounded for anr safety", "MAX_UI_WALK_ENTRIES" in main_src and "private fun File.walkSafe(maxEntries: Int = MAX_UI_WALK_ENTRIES)" in main_src and "if (result.size >= maxEntries) break" in main_src and "projectDirs().take(MAX_PROJECT_DASHBOARD_PROJECTS)" in main_src and "projectRoot.walkSafe(MAX_UI_WALK_ENTRIES)" in main_src)
    require("debug text snapshots render asynchronously and bounded", "openTextToolAsync" in main_src and "truncateTextTool" in main_src and "MAX_TEXT_TOOL_VIEW_BYTES" in main_src and "debugMemorySnapshot()" in main_src.split("openTextToolAsync", 1)[1])
    require("release signing is externalized", 'providers.environmentVariable("PDOCKER_${name}")' in build_gradle_src and "SIGNING_STORE_FILE" in build_gradle_src and "release-signing.properties" in build_gradle_src and "*.jks" in gitignore_src and "*.keystore" in gitignore_src and "*.p12" in gitignore_src)
    require("release apk closes exported debug receiver", 'manifestPlaceholders["pdockerDebugReceiverExported"] = "false"' in build_gradle_src and 'manifestPlaceholders["pdockerDebugReceiverExported"] = "true"' in build_gradle_src and 'android:exported="${pdockerDebugReceiverExported}"' in manifest_src)
    require("docker jobs expose retry actions", "action_retry_job_fmt" in main_src and "retryDockerJob(job)" in main_src)
    require("engine job retry stays on engine api route", "private fun retryDockerJob" in main_src and "runComposeUp(dir, job.title)" in main_src and "runImageBuild(dir, job.title)" in main_src)
    require("docker jobs expose stop and log actions", "stopDockerJob(job.id)" in main_src and "openJobLog(job)" in main_src)
    require("docker jobs recover after missing terminal", "UI was restarted; reconnecting to daemon operation" in main_src and "else openJobLog(job)" in main_src and "job_status_interrupted_fmt" in string_src and "markInterruptedJob" not in main_src)
    require("overview surfaces deduplicated storage metrics", "renderStorageMetrics" in main_src and "StorageMetrics" in main_src and "diskUsage(pdockerHome)" in main_src and "containerPrivateBytes" in main_src and "Os.lstat" in main_src and "storage_total_fmt" in string_src)
    require("overview surfaces daemon active operations", "renderDaemonOperations" in main_src and "/system/operations" in main_src and "DaemonOperation" in main_src and "section_daemon_operations" in string_src)
    require("daemon operations can open job logs", "daemonOperationJob" in main_src and "openJobLog(job)" in main_src and "action_open_job_log_fmt" in main_src)
    require("pdockerd exposes active operations api", "active_operations" in pdockerd_src and 'path == "/system/operations"' in pdockerd_src and "start_operation" in pdockerd_src)
    require("pdockerd accepts diagnostic operation updates", "upsert_operation" in pdockerd_src and 'method == "POST"' in pdockerd_src and "Finished" in pdockerd_src)
    require("ui reconnects running engine jobs after restart", "reconcileDaemonOperationJobs" in main_src and "UI was restarted; reconnecting to daemon operation" in main_src and "reconnected daemon" in main_src and "markInterruptedJob(job)" not in main_src.split("private fun loadDockerJobs", 1)[1].split("private fun saveDockerJobs", 1)[0])
    require("streaming build tolerates client reconnect loss", "except (BrokenPipeError, ConnectionResetError, OSError)" in pdockerd_src)
    require("ui exposes build cache prune", "action_prune_build_cache" in string_src and 'post("/build/prune")' in main_src)
    require("docker ps renders ports without json leakage", "formatPortsForPs" in main_src and 'obj.optJSONArray("Ports")' in main_src)
    require("docker ps surfaces health status", 'f"Up ({health_status})"' in pdockerd_src)
    require("docker ps columns share one formatter", '"CONTAINER ID" to 12' in main_src and '"PORTS" to 30' in main_src and "fun cell(value: String, width: Int)" in main_src)
    require("docker ps columns include separators", 'val separator = "  "' in main_src and "joinToString(separator)" in main_src)
    require("docker ps clipping stays monospace ascii", 'compact.take(width - 3) + "...' in main_src and '"…"' not in main_src.split("private fun formatContainers", 1)[1].split("private fun formatPortsForPs", 1)[0])
    require("container order is stable across refreshes", "containerSnapshotComparator" in main_src and ".sortedWith(containerSnapshotComparator())" in main_src and "compareByDescending<File> { readState(it)?.optString(\"Created\")" in main_src and "containers.sort(key=lambda item:" in pdockerd_src)
    require("container list skips storage sizing unless requested", "def list_containers(all_=False, filters=None, size=False)" in pdockerd_src and 'query.get("size", ["false"])' in pdockerd_src and "collect_storage_summary() if size else" in pdockerd_src)
    require("container tab reconciles state from engine snapshot", "containerSnapshotLookup" in main_src and "refreshContainerSnapshotAsync" in main_src and 'engine.getArray("/containers/json?all=1")' in main_src and 'snapshot?.optString("Status")' in main_src)
    require("compose containers are labelled for project identity", "PDOCKER_PROJECT_ID_LABEL" in main_src and "PDOCKER_COMPOSE_SERVICE_LABEL" in main_src and '"com.docker.compose.service"' in main_src and "projectIdFor(dir)" in main_src)
    require("container ui resolves actions by engine id first", "containerSnapshotFor(dir, state, snapshotLookup)" in main_src and "containerActionTarget(snapshot, state, dir)" in main_src and "snapshot?.optString(\"Id\")" in main_src)
    require("container ui avoids ambiguous duplicate-name snapshot lookup", "ContainerSnapshotLookup" in main_src and "byUniqueName" in main_src and "singleOrNull()" in main_src and "looksLikeContainerEngineId" in main_src)
    require("project cards prefer engine id labels over unambiguous compose names", "projectContainerSnapshots(projectDir: File)" in main_src and "labelledProject == projectId" in main_src and "uniqueContainerSnapshotNames" in main_src and 'startsWith("$projectName-")' not in main_src)
    require("project cards count running state from engine truth helper", "val running = snapshots.count { containerSnapshotIsRunning(it) }" in main_src and 'startsWith("Exited", ignoreCase = true) -> false' in main_src)
    require("project running summary is derived only from engine container snapshots", "projectContainerStatusSummary(projectDir: File)" in main_src and "projectContainerSnapshots(projectDir)" in main_src and "containerSnapshotIsRunning(it)" in main_src and "dockerJobs" not in main_src.split("private fun projectContainerStatusSummary", 1)[1].split("private fun projectContainerSnapshots", 1)[0])
    require("project health summary is explicit compose healthcheck metadata", "private fun projectHealthSummary(services: List<ComposeService>)" in main_src and "services.filter { it.hasHealthcheck }" in main_src and "project_dashboard_health_fmt" in string_src and "Healthchecks declared" in string_src and "ヘルスチェック宣言" in string_src)
    require("project service health requires matching running service", "ProjectServiceUrl" in main_src and "projectRunningServiceNames(projectDir, snapshots)" in main_src and "serviceUrl.serviceName in runningServices" in main_src and "service_health_inactive" in string_src)
    require("service health probes are scheduled only for running http services", "urls.filter { it.serviceName in runningServices && isHttpServiceUrl(it.url) }" in main_src and ".forEach { scheduleServiceHealthProbe(it.url) }" in main_src)
    require("service health wording never treats pending probes as healthy", "Service probe" in string_src and "HTTP probe pending" in string_src and "Engine container not running" in string_src and "healthy" not in string_src and "正常" not in string_src)
    require("project service health reports failed probes as down", 'if (code in 200..399) "HTTP $code" else "down HTTP $code"' in main_src)
    bridge_src_now = (ROOT / "app/src/main/kotlin/io/github/ryo100794/pdocker/Bridge.kt").read_text()
    require("container exposes explicit engine api it terminal", "action_container_terminal_fmt" in string_src and "detail_container_terminal" in string_src and "ENGINE_EXEC_PREFIX" in main_src and "engineExecTerminalCommand" in main_src and "/exec/$execId/start" in bridge_src_now and 'import org.json.JSONArray' in bridge_src_now and "command -v /bin/bash" in bridge_src_now and "exec /bin/bash -i" in bridge_src_now and "exec /bin/sh -i" in bridge_src_now and '"TERM=xterm-256color"' in bridge_src_now and '"COLORTERM=truecolor"' in bridge_src_now and "docker exec -it" not in main_src)
    require("engine exec it uses docker hijack stdin without private stdin api", "PdockerOutOfBandStdin" not in bridge_src_now and "PdockerOutOfBandStdin" not in pdockerd_src and "/stdin" not in bridge_src_now and 're.match(r"^/exec/(.+?)/stdin$"' not in pdockerd_src and "socket.outputStream.write(bytes)" in bridge_src_now and "_pipe_hijacked_stdin(proc)" in pdockerd_src)
    require("container terminal is only offered for running containers", "containerIsRunning(snapshot, state)" in main_src and "if (running) {" in main_src and "Container {cid} is not running" in pdockerd_src)
    require("engine exec terminal opens a fresh session tab", "keyOverride" in main_src and '"engine-exec:${containerId.trim()}:${System.nanoTime()}"' in main_src)
    require("engine exec smoke rejects bracket argument noise", 'pdocker-it-bracket-ok' in android_smoke_src and "pdocker-it-ok" in android_smoke_src and '/usr/bin/[ \\"x\\" = \\"x\\" ]' in android_smoke_src and "grep -Eq '(/usr/bin/)?\\[: extra argument'" in android_smoke_src)
    require("default dev workspace keeps runtime workspace out of build context", "workspace/" in (ROOT / "app/src/main/assets/default-project/.dockerignore").read_text() and "models/" in (ROOT / "app/src/main/assets/default-project/.dockerignore").read_text() and "requiredDockerignore" in main_src)
    require("container terminal wording keeps logs separate", "Attach an interactive shell via Engine exec" in string_src and "Engine exec で対話シェルに接続" in string_src and "Open logs then attach" not in string_src and "ログを表示してから" not in string_src)
    require("engine exec encodes container refs", "DockerEngineClient.encodePath(containerId)" in bridge_src_now and "urllib.parse.unquote(m.group(1))" in pdockerd_src)
    require("container console avoids host shell fallback", "openDockerInteractiveTerminal" in main_src and "ENGINE_EXEC_PREFIX" in main_src and "dockerCommand(" not in main_src.split("private fun openDockerInteractiveTerminal", 1)[1].split("private fun openEditor", 1)[0])
    require("host shell is diagnostic-only", "private fun renderDiagnostics" in main_src and "action_host_shell" in main_src and "Tab.Overview -> renderOverview()" in main_src)
    bench_src = (ROOT / "app/src/main/kotlin/io/github/ryo100794/pdocker/AndroidGpuBench.kt").read_text()
    require("android gpu bench writes cpu and gles reference artifacts", "AndroidGpuBench.run" in main_src and "android-gpu-bench" in bench_src and "vector_add" in bench_src and "saxpy" in bench_src and "matmul_fp32" in bench_src and "cpu_scalar" in bench_src and "gles31_compute" in bench_src and "compile_ms" in bench_src and "action_run_gpu_bench" in string_src)
    require("container cards surface network warnings", "containerWarningSummary" in main_src and "container_warning_ports_metadata" in string_src)
    require("container port wording exposes requested inactive mapping semantics", "containerNetworkSummary" in main_src and "summarizePorts(ports)" in main_src and "Requested ports" in string_src and "requested/inactive until runtime listener proof" in string_src and "要求ポート" in string_src)
    docker_scope_src = (ROOT / "docs/design/DOCKER_COMPAT_SCOPE.md").read_text()
    compat_doc_src = (ROOT / "docs/test/COMPATIBILITY.md").read_text()
    require("docs define port mapping truth states", "`planned`" in docker_scope_src and "`inactive`" in docker_scope_src and "`active`" in docker_scope_src and "`conflict`" in docker_scope_src and "requested Docker port" in docker_scope_src and "metadata remains `inactive`" in docker_scope_src)
    require("compat docs keep service health tied to engine container proof", "prove the listener belongs to the current Engine container ID" in compat_doc_src and "must not display healthy" in compat_doc_src and "configured ports" in compat_doc_src)
    require("container cards open compose-declared service ports", "containerServiceUrls" in main_src and "containerServiceLabels" in main_src and "PDOCKER_SERVICE_URL_LABEL_PREFIX" in main_src)
    require("service actions distinguish VNC clients from browser URLs", "serviceUriFor" in main_src and '"vnc://$host:$hostPort"' in main_src and "action_open_vnc_service_fmt" in string_src and "detail_open_vnc_client_fmt" in string_src)
    require("raw VNC ports are not opened as HTTP", "ComposePortBinding" in main_src and "containerPort in 5900..5999" in main_src and "hostPort in 5900..5999" in main_src and '"novnc" in lower' in main_src and "return false" in main_src)
    require("project library blender raw VNC opens as VNC while noVNC stays HTTP", "15901:5901" in blender_compose and "18083=noVNC Blender" in blender_compose and "containerPort in 5900..5999" in main_src and '"novnc" in lower' in main_src)
    require("non-http service actions skip HTTP health probes", "isHttpServiceUrl(it.url)" in main_src and "service_health_external_client" in string_src and 'if (!isHttpServiceUrl(url)) return "external client"' in main_src)
    require("explicit service metadata allows VNC URIs", "isServiceUri(right)" in main_src and "isServiceUri(url)" in main_src)
    require("ros2 rviz template exposes noVNC and raw VNC host ports", "18082:6080" in ros2_rviz_compose and "15900:5900" in ros2_rviz_compose and "pdocker.service-url: 18082=noVNC RViz" in ros2_rviz_compose)
    require("container cards expose lifecycle actions", "action_container_start_fmt" in string_src and "/start" in main_src and "/stop" in main_src and "logs(target" in main_src)
    require("container lifecycle avoids docker cli shell", "DockerEngineClient" in main_src and "runContainerAction" in main_src)
    require("image pull uses engine api with searchable refs", "showPullImageDialog" in main_src and "runPullImage(image)" in main_src and "fetchDockerHubImageRefs" in main_src and "currentImagePlatform" in main_src and "abiDefaultImagePlatform" in main_src and "pullImage(image)" in main_src and "pullImage(\"ubuntu:22.04\")" not in main_src and "/images/create?fromImage=" in engine_src and "Open docker pull shell" not in string_src and "docker pull 用シェル" not in (ROOT / "app/src/main/res/values-ja/strings.xml").read_text())
    require("image pull stages layers and tags atomically", "_layer_exists(diff_id)" in pdockerd_src and ".tmp-" in pdockerd_src and ".pull-" in pdockerd_src and ".old-" in pdockerd_src and "with open(os.path.join(stage, \"platform\"), \"w\")" in pdockerd_src)
    require("images tab can delete bad tagged images", "deleteImage(imageRef)" in main_src and 'request("DELETE", "/images/${encodePath(image)}"' in engine_src and "confirmDeleteImage" in main_src and "action_delete_image_fmt" in string_src)
    require("images tab can clean build cache after image delete", "runPruneBuildCache" in main_src and "pruneBuildCache()" in engine_src and "cleanCache" in main_src and "action_clean_image_cache_fmt" in string_src)
    require("images tab renders reference graph with sizes", "renderImageReferenceTree" in main_src and "imageParentMap" in main_src and "uniqueLayerBytes" in main_src and "sharedLayerBytes" in main_src and "addImageReferenceGraph" in main_src and "ImageReferenceGraphRow" in main_src and "ImageGraphLayout" in main_src and "canvas.drawLine" in main_src and "image_reference_legend_image" in string_src and "image_storage_detail_fmt" in string_src and "image_version_detail_fmt" in string_src)
    require("image reference graph owns details and actions", "ImageGraphAction" in main_src and "imageDetail(image.dir, image.ref, image)" in main_src and "openImageFiles(image.dir)" in main_src and "confirmDeleteImage(image.ref, cleanCache = true)" in main_src and "image_reference_action_files" in string_src)
    require("dockerfile builds use streaming engine api", "runImageBuild" in main_src and "buildImageStreaming(dir" in main_src and "requestJsonStream" in engine_src and "/build?t=" in engine_src)
    require("dockerfile copy supports wildcard sources", "import glob" in pdockerd_src and "_copy_source_matches" in pdockerd_src and "glob.has_magic" in pdockerd_src and "matches = _copy_source_matches(context_dir, s)" in pdockerd_src and "return fail_build()" in pdockerd_src)
    require("compose up streams build output into ui jobs", "buildImageStreaming(contextDir, image)" in main_src and "emit(buildLine)" in main_src and "openLiveJobLog(job" in main_src)
    require("compose up blocks start after any build stream failure", "containsBuildFailure(text)" in engine_src and "containsBuildSuccess(text, tag)" in engine_src and "build did not complete successfully" in engine_src and 'optJSONObject("errorDetail")' in engine_src and "ERROR: build failed" in engine_src and "buildImageStreaming(contextDir, image)" in main_src and "Build blocked by current container runtime" not in main_src)
    require("android build context honors dockerignore", "DockerIgnore.load" in (ROOT / "app/src/main/kotlin/io/github/ryo100794/pdocker/DockerEngineClient.kt").read_text() and "models/" in (ROOT / "app/src/main/assets/project-library/llama-cpp-gpu/.dockerignore").read_text())
    require("compose up links header-declared services after successful start", "Service URL $label $url" in main_src and "openServiceWhenReady" in main_src and "ACTION_VIEW" in main_src and "parseComposeHeaderServiceLinks" in main_src and "pdocker.auto-open:" in main_src)
    require("container create allows slow rootfs materialization", "fun postJson(path: String, json: JSONObject, timeoutMs: Int = 30_000)" in engine_src and "postJson(path, config, timeoutMs = 900_000)" in engine_src)
    require("compose up uses in-app orchestrator", "runComposeUp" in main_src and "parseComposeServices" in main_src and "/containers/create" in engine_src)
    require("compose gpu requests include docker capabilities", '"pdocker-gpu"' in main_src and '"Capabilities"' in main_src and '"gpu"' in main_src and '"pdocker.gpu"' in main_src and '"pdocker.opencl"' in main_src)
    require("gpu bridge env migrates existing container state on start", "_merge_runtime_bridge_env(state)" in pdockerd_src and "PDOCKER_GPU_VIRTUAL_MEMORY" in pdockerd_src and "GGML_VK_SUBALLOCATION_BLOCK_SIZE" in pdockerd_src)
    require("compose resource memory keys feed engine metadata", '"mem_limit"' in main_src and '"memswap_limit"' in main_src and "deployMemoryLimit" in main_src and '"Memory"' in main_src and '"MemorySwap"' in main_src and "parseMemoryBytes" in main_src)
    require("compose memory pager is explicit pdocker opt-in", "PDOCKER_MEMORY_PAGER" in main_src and "PDOCKER_MEMORY_PAGER_MAX_BYTES" in main_src and "io.pdocker.memory-pager" in main_src and "io.pdocker.memory-pager.limit-bytes" in main_src)
    require("compose up never creates inspection containers after failed build", "Prepared for inspection" not in main_src and "dockerfileBaseImage" not in main_src and "using materialized base image" not in main_src)
    require("engine job output is deduplicated", "appendUniqueLines" in main_src and "existing.add" in main_src)
    require("android runtime preflight is enabled", "PDOCKER_RUNTIME_PREFLIGHT" in pdockerd_bridge_src)
    require("debug smoke can start daemon through activity", "ACTION_SMOKE_START" in main_src and "FLAG_DEBUGGABLE" in main_src and ".PdockerdService" not in android_smoke_src)
    require("device scripts resolve flavor activity class", "$CLASS_PREFIX.MainActivity" in android_smoke_src and "cmd package resolve-activity --brief" in api29_feasibility_src and "$PKG/.MainActivity" not in api29_feasibility_src)
    require("llama gpu compare starts daemon without foregrounding ui", "start_daemon_for_test" in llama_compare_src and "PdockerdDebugReceiver" in llama_compare_src and ".MainActivity" not in llama_compare_src.split("wait_for_engine()", 1)[1].split("urlencode()", 1)[0])
    require("adb scripts avoid monkey rotation side effects", "monkey -p" not in (ROOT / "scripts/android-gpu-host-bench.sh").read_text() and "monkey -p" not in (ROOT / "scripts/android-gpu-compare-bench.sh").read_text() and "monkey -p" not in (ROOT / "docs/test/APK_MEMORY_PAGER_PROBE.md").read_text())
    require("debug smoke can start compose through main ui route", "ACTION_SMOKE_COMPOSE_UP" in main_src and "runComposeUp(dir" in main_src and 'getString(R.string.terminal_compose_up_fmt, project)' in main_src)
    require("debug smoke can run gpu bench", "ACTION_SMOKE_GPU_BENCH" in main_src and "PdockerdDebugReceiver" in manifest_src and "AndroidGpuBench.run" in debug_receiver_src and "am broadcast" in android_smoke_src and "android-gpu-bench-*.jsonl" in android_smoke_src and 'android:launchMode="singleTop"' in manifest_src)
    require("terminals label their origin", "terminalSessionCommand" in main_src and "PDOCKER_TERMINAL_TITLE" in main_src)
    require("existing templates migrate service ports", "migrateProjectPorts" in main_src and "8080:8080" in main_src and "18080:18080" in main_src)
    require("template install reports copied and kept files", "copyAssetTreeMissing" in main_src and "TemplateInstallReport" in main_src and "status_library_install_report_fmt" in string_src)
    require("template install records version stamp", ".pdocker-template-id" in main_src and ".pdocker-template-version" in main_src and "obj.optInt(\"version\", libraryVersion)" in main_src)
    require("android device smoke script exists", "docker compose up --detach --build" in android_smoke_src and "run-as" in android_smoke_src and "docker version" in android_smoke_src)
    require("android device smoke covers engine exec path", "docker exec \\\"\\$CID\\\" sh -lc" in android_smoke_src and "pdocker-exec-ok" in android_smoke_src and "'/vendor/xbin'" in android_smoke_src and "sleep 300" in android_smoke_src)
    require("android device smoke covers engine api it stream", "engine_exec_it_smoke" in android_smoke_src and "/containers/$container_ref/exec" in android_smoke_src and "/exec/%s/start" in android_smoke_src and "pdocker-it-ok" in android_smoke_src)
    require("android device smoke covers ui bridge it self-test", "ACTION_SMOKE_UI_IT_SELFTEST" in main_src and "runUiItSelfTest" in main_src and "ui-it-selftest-latest.json" in main_src and "ui_engine_exec_it_selftest" in android_smoke_src and "SMOKE_UI_IT_SELFTEST" in android_smoke_src and "pdocker-ui-it-ok" in main_src and "pdocker-ui-it-bracket-ok" in main_src and "pdocker-ui-it-ctrlc-ok" in main_src and "pdocker-ui-it-term-ok" in main_src and "pdocker-ui-it-bash-ok" in main_src and "window.pdockerTestSendInput" in main_src)
    require("android device smoke avoids orphan cleanup side effects", "--remove-orphans" not in android_smoke_src)
    require("android device smoke does not force-stop by default", "PDOCKER_SMOKE_FORCE_STOP" in android_smoke_src and '== "1"' in android_smoke_src and "force-stopping app; running containers will stop" in android_smoke_src)

    require("image browser accepts selected image extra", "EXTRA_IMAGE_NAME" in image_src)
    require("image browser accepts selected container extra", "EXTRA_CONTAINER_ID" in image_src)
    require("debug resources pane browses app-owned roots", "Tab.Debug" in main_src and "renderDebugResources" in main_src and "openDebugResources" in main_src and "EXTRA_ROOT_PATH" in image_src and "isAllowedDebugRoot" in image_src and "section_debug_resources" in string_src)
    require("debug resources pane exposes memory process and handle snapshots", "debugMemorySnapshot" in main_src and "debugProcessSnapshot" in main_src and "debugHandleSnapshot" in main_src and "/proc/meminfo" in main_src and "/fd" in main_src and "action_debug_handles" in string_src)
    require("debug root browser back exits instead of images fallback", "standaloneRoot" in image_src and "finish()" in image_src.split("if (standaloneRoot)", 1)[1].split("currentMergedLower", 1)[0])
    require("selected image browser back returns to caller", "selectedImage != null" in image_src and "standaloneRoot = true" in image_src.split("selectedImage != null", 1)[1].split("selectedContainer != null", 1)[0])
    require("file browser rows are explorer-style single rows", "orientation = LinearLayout.HORIZONTAL" in image_src.split("private fun addRow", 1)[1].split("private fun addMessage", 1)[0] and "ellipsize = TextUtils.TruncateAt.MIDDLE" in image_src.split("private fun addRow", 1)[1].split("private fun addMessage", 1)[0])
    require("image rows deep-link to selected image", "openImageFiles(image.dir)" in main_src)
    require("generic image browser action remains available", "openImageFiles()" in main_src)
    require("container rows deep-link to container files", "openContainerFiles(dir)" in main_src and "action_browse_container_files_fmt" in string_src)
    require("image/container files copy into editable projects", "copyFileToProject" in image_src and "TextEditorActivity.EXTRA_PATH" in image_src)
    require("container files expose writable overlay editing", "containerBrowserRoots" in image_src and "copyToOverlayAndOpen" in image_src and "EXTRA_ROOT_PATH" in editor_activity_src)
    require("container files expose merged lower upper view", "mergedEntries" in image_src and ".wh..wh..opq" in image_src and "title_container_merged_files_fmt" in string_src)

    require("editor tabs are keyed by canonical file path", "val key = target.absolutePath" in main_src)
    require("same-name editors get parent-qualified titles", "private fun editorTitle" in main_src)
    require("project files are surfaced as editor shortcuts", "renderProjectFileShortcuts" in main_src and "section_project_files" in string_src)
    require("project dashboard summarizes compose/dockerfile/files", "renderProjectDashboard" in main_src and "private data class ProjectSummary" in main_src and "section_project_dashboard" in string_src)
    require("project dashboard opens primary files and actions", "openProjectPrimaryFile" in main_src and "action_open_project_compose_fmt" in string_src and "action_open_project_dockerfile_fmt" in string_src)
    require("project dashboard tracks services jobs containers", "projectContainerStatusSummary" in main_src and "projectJobSummary" in main_src and "parseComposeServices" in main_src)
    require("project dashboard surfaces latest build job failure reason", "jobFailureReason" in main_src and "BLAS not found" in main_src and "Connection reset" in main_src and "latestFailure" in main_src)
    require("project dashboard exposes compose-declared service URLs", "projectServiceUrls" in main_src and "composeServiceUrls" in main_src and "composePortBinding" in main_src and "project_dashboard_urls_fmt" in string_src)
    require("project dashboard probes service health", "projectServiceHealthSummary" in main_src and "scheduleServiceHealthProbe" in main_src and "HttpURLConnection" in main_src and "project_dashboard_service_health_fmt" in string_src)
    require("project dashboard surfaces compose dependencies", "dependsOn" in main_src and "projectDependencySummary" in main_src and "project_dashboard_dependencies_fmt" in string_src)
    require("project dashboard surfaces compose healthchecks", "hasHealthcheck" in main_src and "projectHealthSummary" in main_src and "project_dashboard_health_fmt" in string_src)
    require("project dashboard surfaces llama model and gpu diagnostics", "projectModelSummary" in main_src and "projectGpuProfileSummary" in main_src and "pdocker-gpu-diagnostics.json" in main_src and "project_dashboard_models_fmt" in string_src and "action_open_gpu_diagnostics" in string_src)
    require("project dashboard surfaces runtime failure diagnostics", "projectRuntimeDiagnostic" in main_src and "runtimeFailureReason" in main_src and "project_dashboard_runtime_fmt" in string_src and "action_open_runtime_diagnostics" in string_src and "unsafe path" in main_src and "Cross-device link" in main_src)
    require("overview avoids duplicate daemon-linked job cards", "val daemonJobIds = daemonOperations.mapNotNull { daemonOperationJob(it)?.id }.toSet()" in main_src and "renderDockerJobs { it.id !in daemonJobIds }" in main_src)
    require("default dev workspace migrates codex and claude code plugins", "migrateDefaultDevWorkspace" in main_src and "OpenAI.chatgpt" in main_src and "Anthropic.claude-code" in main_src and "CLAUDE_CODE_NPM_PACKAGE" in main_src and "ANTHROPIC_API_KEY" in main_src)
    require("default dev workspace repairs placeholder dockerfile", "repairDefaultDevWorkspaceDockerfile" in main_src and "Dockerfile.pdocker-broken-backup" in main_src and "default-project/Dockerfile" in main_src and "echo hello from Dockerfile" in main_src)
    require("default dockerfile editor fallback uses bundled workspace asset", "defaultEditorContent(file" in main_src and 'assets.open("default-project/Dockerfile")' in main_src and "defaultContent(file" in editor_activity_src and 'assets.open("default-project/Dockerfile")' in editor_activity_src)
    require("default dev workspace installs hidden volume extensions at runtime", "install_extension_if_missing" in (ROOT / "app/src/main/assets/default-project/scripts/start-code-server.sh").read_text() and "OpenAI.chatgpt" in (ROOT / "app/src/main/assets/default-project/scripts/start-code-server.sh").read_text() and "Anthropic.claude-code" in (ROOT / "app/src/main/assets/default-project/scripts/start-code-server.sh").read_text())
    require("default dev workspace exposes codex task", "Codex: start" in main_src and (ROOT / "app/src/main/assets/default-project/workspace/.vscode/tasks.json").read_text().count("Codex:") >= 2)

    require("interactive terminal font remains 12pt", "const initialFontSize = readOnly ? 8 : 12" in xterm_src and "fontSize: initialFontSize" in xterm_src)
    require("terminal shortcut key palette is present", 'id="keybar"' in xterm_src and 'data-toggle="ctrl"' in xterm_src)
    require("terminal input normalizes ime enter and releases one-shot modifiers", "normalizeTerminalInput" in xterm_src and "replace(/\\r\\n/g, '\\r').replace(/\\n/g, '\\r')" in xterm_src and "clearTransientModifiers" in xterm_src and "scheduleModifierClear" in xterm_src and "claimImeEvent" in xterm_src and "stopImmediatePropagation" in xterm_src and "installHelperInputFallback" in xterm_src and "inputType === 'insertLineBreak'" in xterm_src and "suppressTerminalDataOnce(event.data)" in xterm_src and "consumeSuppressedTerminalData(data)" in xterm_src and "consumeSuppressedTerminalData(event.data)" in xterm_src and "consumeSuppressedTerminalData(ta.value)" in xterm_src and "window.pdockerTestSendInput" in xterm_src and "window.pdockerTestCtrlInput" in xterm_src and "pdocker-ui-it-ctrlc-ok" in main_src)
    require("terminal supports pinch zoom", "setFontSize" in xterm_src and "event.touches.length === 2" in xterm_src)
    require("terminal touch scroll remains available", "viewport.scrollTop -= deltaY" in xterm_src and "touchScroll" in xterm_src and "touchScrollThreshold" in xterm_src)
    require("terminal shows touch selection markers", "selection-handle" in xterm_src and "term.select(" in xterm_src and "data-toggle=\"select\"" in xterm_src)
    require("terminal select-all is wired", "data-select-all=\"1\"" in xterm_src and "selectAllTerminal" in xterm_src and "term.selectAll()" in xterm_src)
    require("terminal selection menu touch does not steal button clicks", "selectionMenu.contains(event.target)" in xterm_src and "event.stopPropagation()" in xterm_src)
    require("terminal copy uses android clipboard bridge", "copyToClipboard" in bridge_src and "PdockerBridge.copyToClipboard" in xterm_src)
    require("terminal selection handles drag independently", "roleForVisualHandle" in xterm_src and "selectionDrag = roleForVisualHandle" in xterm_src and "pointer-events: auto" in xterm_src)
    require("terminal selection accounts for scrollback viewport", "viewportY()" in xterm_src and "term.buffer.active.viewportY" in xterm_src and "cell.y - viewportY()" in xterm_src)
    require("terminal selection suppresses soft keyboard", "suppressImeForSelection" in xterm_src and "selectionSuppressesIme()" in xterm_src and "ta.setAttribute('inputmode', 'none')" in xterm_src and "ta.blur()" in xterm_src and "if (selectionSuppressesIme())" in xterm_src)
    require("readonly terminal selection actions keep ime suppressed", "runSelectionAction" in xterm_src and "if (readOnly) suppressImeForSelection()" in xterm_src and "if (readOnly || selectionSuppressesIme()) suppressImeForSelection()" in xterm_src)

    require("code editor exposes whitespace", "VisibleWhitespaceTransformation" in editor_src)
    require("code editor keeps indent/outdent actions", "indentSelection()" in editor_src and "outdentSelection()" in editor_src)
    require("code editor supports search and replace", "findNext()" in editor_src and "replaceAllMatches()" in editor_src)
    require("code editor supports pinch zoom", "ScaleGestureDetector" in editor_src and "editorFontSize" in editor_src)
    require("code editor syncs line numbers while scrolling", "setOnScrollChangeListener" in editor_src and "lineNumbers.scrollY = editor.scrollY" in editor_src)
    require("code editor supports forgiving horizontal drag scroll", "horizontalPan" in editor_src and "horizontalScroller.scrollBy" in editor_src and "abs(totalDx) > abs(totalDy) * 0.55f" in editor_src)

    require("localized terminal title formats exist", "terminal_compose_up_fmt" in string_src and "terminal_docker_build_fmt" in string_src)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
